// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: contenthubs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenSteamworks.Protobuf {

  /// <summary>Holder for reflection information generated from contenthubs.proto</summary>
  public static partial class ContenthubsReflection {

    #region Descriptor
    /// <summary>File descriptor for contenthubs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ContenthubsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFjb250ZW50aHVicy5wcm90bxogZ29vZ2xlL3Byb3RvYnVmL2Rlc2NyaXB0",
            "b3IucHJvdG8aGHN0ZWFtbWVzc2FnZXNfYmFzZS5wcm90byLfBAoQQ1N0b3Jl",
            "UGFnZUZpbHRlchI1CgtzYWxlX2ZpbHRlchgBIAEoCzIgLkNTdG9yZVBhZ2VG",
            "aWx0ZXIuU2FsZVBhZ2VGaWx0ZXISPgoSY29udGVudF9odWJfZmlsdGVyGAIg",
            "ASgLMiIuQ1N0b3JlUGFnZUZpbHRlci5Db250ZW50SHViRmlsdGVyEjQKDXN0",
            "b3JlX2ZpbHRlcnMYAyADKAsyHS5DU3RvcmVQYWdlRmlsdGVyLlN0b3JlRmls",
            "dGVyGiQKDlNhbGVQYWdlRmlsdGVyEhIKCnNhbGVfdGFnaWQYASABKA0awAIK",
            "EENvbnRlbnRIdWJGaWx0ZXISEAoIaHViX3R5cGUYASABKAkSFAoMaHViX2Nh",
            "dGVnb3J5GAIgASgJEhEKCWh1Yl90YWdpZBgDIAEoDRJbCg9kaXNjb3VudF9m",
            "aWx0ZXIYBCABKA4yHi5FQ29udGVudEh1YkRpc2NvdW50RmlsdGVyVHlwZToi",
            "RUNvbnRlbnRIdWJEaXNjb3VudEZpbHRlclR5cGVfTm9uZRI7CgVvcHRpbhgF",
            "IAEoCzIsLkNTdG9yZVBhZ2VGaWx0ZXIuQ29udGVudEh1YkZpbHRlci5PcHRJ",
            "bkluZm8aVwoJT3B0SW5JbmZvEgwKBG5hbWUYASABKAkSEwoLb3B0aW5fdGFn",
            "aWQYAiABKA0SEwoLcHJ1bmVfdGFnaWQYAyABKA0SEgoKb3B0aW5fb25seRgE",
            "IAEoCBo1CgtTdG9yZUZpbHRlchITCgtmaWx0ZXJfanNvbhgBIAEoCRIRCglj",
            "YWNoZV9rZXkYAiABKAkqrwEKHUVDb250ZW50SHViRGlzY291bnRGaWx0ZXJU",
            "eXBlEiYKIkVDb250ZW50SHViRGlzY291bnRGaWx0ZXJUeXBlX05vbmUQABIv",
            "CitFQ29udGVudEh1YkRpc2NvdW50RmlsdGVyVHlwZV9EaXNjb3VudHNPbmx5",
            "EAESNQoxRUNvbnRlbnRIdWJEaXNjb3VudEZpbHRlclR5cGVfUHJpb3JpdGl6",
            "ZURpc2NvdW50cxACQiNIAYABAaoCF09wZW5TdGVhbXdvcmtzLlByb3RvYnVm",
            "gLUYAQ=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, global::OpenSteamworks.Protobuf.SteammessagesBaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::OpenSteamworks.Protobuf.EContentHubDiscountFilterType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.CStorePageFilter), global::OpenSteamworks.Protobuf.CStorePageFilter.Parser, new[]{ "SaleFilter", "ContentHubFilter", "StoreFilters" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.CStorePageFilter.Types.SalePageFilter), global::OpenSteamworks.Protobuf.CStorePageFilter.Types.SalePageFilter.Parser, new[]{ "SaleTagid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter), global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter.Parser, new[]{ "HubType", "HubCategory", "HubTagid", "DiscountFilter", "Optin" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter.Types.OptInInfo), global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter.Types.OptInInfo.Parser, new[]{ "Name", "OptinTagid", "PruneTagid", "OptinOnly" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.CStorePageFilter.Types.StoreFilter), global::OpenSteamworks.Protobuf.CStorePageFilter.Types.StoreFilter.Parser, new[]{ "FilterJson", "CacheKey" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  public enum EContentHubDiscountFilterType {
    [pbr::OriginalName("EContentHubDiscountFilterType_None")] None = 0,
    [pbr::OriginalName("EContentHubDiscountFilterType_DiscountsOnly")] DiscountsOnly = 1,
    [pbr::OriginalName("EContentHubDiscountFilterType_PrioritizeDiscounts")] PrioritizeDiscounts = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CStorePageFilter : pb::IMessage<CStorePageFilter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CStorePageFilter> _parser = new pb::MessageParser<CStorePageFilter>(() => new CStorePageFilter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CStorePageFilter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.ContenthubsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CStorePageFilter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CStorePageFilter(CStorePageFilter other) : this() {
      saleFilter_ = other.saleFilter_ != null ? other.saleFilter_.Clone() : null;
      contentHubFilter_ = other.contentHubFilter_ != null ? other.contentHubFilter_.Clone() : null;
      storeFilters_ = other.storeFilters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CStorePageFilter Clone() {
      return new CStorePageFilter(this);
    }

    /// <summary>Field number for the "sale_filter" field.</summary>
    public const int SaleFilterFieldNumber = 1;
    private global::OpenSteamworks.Protobuf.CStorePageFilter.Types.SalePageFilter saleFilter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenSteamworks.Protobuf.CStorePageFilter.Types.SalePageFilter SaleFilter {
      get { return saleFilter_; }
      set {
        saleFilter_ = value;
      }
    }

    /// <summary>Field number for the "content_hub_filter" field.</summary>
    public const int ContentHubFilterFieldNumber = 2;
    private global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter contentHubFilter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter ContentHubFilter {
      get { return contentHubFilter_; }
      set {
        contentHubFilter_ = value;
      }
    }

    /// <summary>Field number for the "store_filters" field.</summary>
    public const int StoreFiltersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::OpenSteamworks.Protobuf.CStorePageFilter.Types.StoreFilter> _repeated_storeFilters_codec
        = pb::FieldCodec.ForMessage(26, global::OpenSteamworks.Protobuf.CStorePageFilter.Types.StoreFilter.Parser);
    private readonly pbc::RepeatedField<global::OpenSteamworks.Protobuf.CStorePageFilter.Types.StoreFilter> storeFilters_ = new pbc::RepeatedField<global::OpenSteamworks.Protobuf.CStorePageFilter.Types.StoreFilter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenSteamworks.Protobuf.CStorePageFilter.Types.StoreFilter> StoreFilters {
      get { return storeFilters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CStorePageFilter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CStorePageFilter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SaleFilter, other.SaleFilter)) return false;
      if (!object.Equals(ContentHubFilter, other.ContentHubFilter)) return false;
      if(!storeFilters_.Equals(other.storeFilters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (saleFilter_ != null) hash ^= SaleFilter.GetHashCode();
      if (contentHubFilter_ != null) hash ^= ContentHubFilter.GetHashCode();
      hash ^= storeFilters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (saleFilter_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SaleFilter);
      }
      if (contentHubFilter_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ContentHubFilter);
      }
      storeFilters_.WriteTo(output, _repeated_storeFilters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (saleFilter_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SaleFilter);
      }
      if (contentHubFilter_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ContentHubFilter);
      }
      storeFilters_.WriteTo(ref output, _repeated_storeFilters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (saleFilter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SaleFilter);
      }
      if (contentHubFilter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ContentHubFilter);
      }
      size += storeFilters_.CalculateSize(_repeated_storeFilters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CStorePageFilter other) {
      if (other == null) {
        return;
      }
      if (other.saleFilter_ != null) {
        if (saleFilter_ == null) {
          SaleFilter = new global::OpenSteamworks.Protobuf.CStorePageFilter.Types.SalePageFilter();
        }
        SaleFilter.MergeFrom(other.SaleFilter);
      }
      if (other.contentHubFilter_ != null) {
        if (contentHubFilter_ == null) {
          ContentHubFilter = new global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter();
        }
        ContentHubFilter.MergeFrom(other.ContentHubFilter);
      }
      storeFilters_.Add(other.storeFilters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (saleFilter_ == null) {
              SaleFilter = new global::OpenSteamworks.Protobuf.CStorePageFilter.Types.SalePageFilter();
            }
            input.ReadMessage(SaleFilter);
            break;
          }
          case 18: {
            if (contentHubFilter_ == null) {
              ContentHubFilter = new global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter();
            }
            input.ReadMessage(ContentHubFilter);
            break;
          }
          case 26: {
            storeFilters_.AddEntriesFrom(input, _repeated_storeFilters_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (saleFilter_ == null) {
              SaleFilter = new global::OpenSteamworks.Protobuf.CStorePageFilter.Types.SalePageFilter();
            }
            input.ReadMessage(SaleFilter);
            break;
          }
          case 18: {
            if (contentHubFilter_ == null) {
              ContentHubFilter = new global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter();
            }
            input.ReadMessage(ContentHubFilter);
            break;
          }
          case 26: {
            storeFilters_.AddEntriesFrom(ref input, _repeated_storeFilters_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CStorePageFilter message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class SalePageFilter : pb::IMessage<SalePageFilter>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<SalePageFilter> _parser = new pb::MessageParser<SalePageFilter>(() => new SalePageFilter());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SalePageFilter> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::OpenSteamworks.Protobuf.CStorePageFilter.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SalePageFilter() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SalePageFilter(SalePageFilter other) : this() {
          _hasBits0 = other._hasBits0;
          saleTagid_ = other.saleTagid_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SalePageFilter Clone() {
          return new SalePageFilter(this);
        }

        /// <summary>Field number for the "sale_tagid" field.</summary>
        public const int SaleTagidFieldNumber = 1;
        private readonly static uint SaleTagidDefaultValue = 0;

        private uint saleTagid_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint SaleTagid {
          get { if ((_hasBits0 & 1) != 0) { return saleTagid_; } else { return SaleTagidDefaultValue; } }
          set {
            _hasBits0 |= 1;
            saleTagid_ = value;
          }
        }
        /// <summary>Gets whether the "sale_tagid" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasSaleTagid {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "sale_tagid" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearSaleTagid() {
          _hasBits0 &= ~1;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as SalePageFilter);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SalePageFilter other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (SaleTagid != other.SaleTagid) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasSaleTagid) hash ^= SaleTagid.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasSaleTagid) {
            output.WriteRawTag(8);
            output.WriteUInt32(SaleTagid);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasSaleTagid) {
            output.WriteRawTag(8);
            output.WriteUInt32(SaleTagid);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasSaleTagid) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SaleTagid);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SalePageFilter other) {
          if (other == null) {
            return;
          }
          if (other.HasSaleTagid) {
            SaleTagid = other.SaleTagid;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                SaleTagid = input.ReadUInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                SaleTagid = input.ReadUInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class ContentHubFilter : pb::IMessage<ContentHubFilter>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ContentHubFilter> _parser = new pb::MessageParser<ContentHubFilter>(() => new ContentHubFilter());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ContentHubFilter> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::OpenSteamworks.Protobuf.CStorePageFilter.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ContentHubFilter() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ContentHubFilter(ContentHubFilter other) : this() {
          _hasBits0 = other._hasBits0;
          hubType_ = other.hubType_;
          hubCategory_ = other.hubCategory_;
          hubTagid_ = other.hubTagid_;
          discountFilter_ = other.discountFilter_;
          optin_ = other.optin_ != null ? other.optin_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ContentHubFilter Clone() {
          return new ContentHubFilter(this);
        }

        /// <summary>Field number for the "hub_type" field.</summary>
        public const int HubTypeFieldNumber = 1;
        private readonly static string HubTypeDefaultValue = "";

        private string hubType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string HubType {
          get { return hubType_ ?? HubTypeDefaultValue; }
          set {
            hubType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "hub_type" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasHubType {
          get { return hubType_ != null; }
        }
        /// <summary>Clears the value of the "hub_type" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearHubType() {
          hubType_ = null;
        }

        /// <summary>Field number for the "hub_category" field.</summary>
        public const int HubCategoryFieldNumber = 2;
        private readonly static string HubCategoryDefaultValue = "";

        private string hubCategory_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string HubCategory {
          get { return hubCategory_ ?? HubCategoryDefaultValue; }
          set {
            hubCategory_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "hub_category" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasHubCategory {
          get { return hubCategory_ != null; }
        }
        /// <summary>Clears the value of the "hub_category" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearHubCategory() {
          hubCategory_ = null;
        }

        /// <summary>Field number for the "hub_tagid" field.</summary>
        public const int HubTagidFieldNumber = 3;
        private readonly static uint HubTagidDefaultValue = 0;

        private uint hubTagid_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint HubTagid {
          get { if ((_hasBits0 & 1) != 0) { return hubTagid_; } else { return HubTagidDefaultValue; } }
          set {
            _hasBits0 |= 1;
            hubTagid_ = value;
          }
        }
        /// <summary>Gets whether the "hub_tagid" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasHubTagid {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "hub_tagid" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearHubTagid() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "discount_filter" field.</summary>
        public const int DiscountFilterFieldNumber = 4;
        private readonly static global::OpenSteamworks.Protobuf.EContentHubDiscountFilterType DiscountFilterDefaultValue = global::OpenSteamworks.Protobuf.EContentHubDiscountFilterType.None;

        private global::OpenSteamworks.Protobuf.EContentHubDiscountFilterType discountFilter_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::OpenSteamworks.Protobuf.EContentHubDiscountFilterType DiscountFilter {
          get { if ((_hasBits0 & 2) != 0) { return discountFilter_; } else { return DiscountFilterDefaultValue; } }
          set {
            _hasBits0 |= 2;
            discountFilter_ = value;
          }
        }
        /// <summary>Gets whether the "discount_filter" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasDiscountFilter {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "discount_filter" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDiscountFilter() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "optin" field.</summary>
        public const int OptinFieldNumber = 5;
        private global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter.Types.OptInInfo optin_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter.Types.OptInInfo Optin {
          get { return optin_; }
          set {
            optin_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ContentHubFilter);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ContentHubFilter other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (HubType != other.HubType) return false;
          if (HubCategory != other.HubCategory) return false;
          if (HubTagid != other.HubTagid) return false;
          if (DiscountFilter != other.DiscountFilter) return false;
          if (!object.Equals(Optin, other.Optin)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasHubType) hash ^= HubType.GetHashCode();
          if (HasHubCategory) hash ^= HubCategory.GetHashCode();
          if (HasHubTagid) hash ^= HubTagid.GetHashCode();
          if (HasDiscountFilter) hash ^= DiscountFilter.GetHashCode();
          if (optin_ != null) hash ^= Optin.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasHubType) {
            output.WriteRawTag(10);
            output.WriteString(HubType);
          }
          if (HasHubCategory) {
            output.WriteRawTag(18);
            output.WriteString(HubCategory);
          }
          if (HasHubTagid) {
            output.WriteRawTag(24);
            output.WriteUInt32(HubTagid);
          }
          if (HasDiscountFilter) {
            output.WriteRawTag(32);
            output.WriteEnum((int) DiscountFilter);
          }
          if (optin_ != null) {
            output.WriteRawTag(42);
            output.WriteMessage(Optin);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasHubType) {
            output.WriteRawTag(10);
            output.WriteString(HubType);
          }
          if (HasHubCategory) {
            output.WriteRawTag(18);
            output.WriteString(HubCategory);
          }
          if (HasHubTagid) {
            output.WriteRawTag(24);
            output.WriteUInt32(HubTagid);
          }
          if (HasDiscountFilter) {
            output.WriteRawTag(32);
            output.WriteEnum((int) DiscountFilter);
          }
          if (optin_ != null) {
            output.WriteRawTag(42);
            output.WriteMessage(Optin);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasHubType) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(HubType);
          }
          if (HasHubCategory) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(HubCategory);
          }
          if (HasHubTagid) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HubTagid);
          }
          if (HasDiscountFilter) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DiscountFilter);
          }
          if (optin_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Optin);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ContentHubFilter other) {
          if (other == null) {
            return;
          }
          if (other.HasHubType) {
            HubType = other.HubType;
          }
          if (other.HasHubCategory) {
            HubCategory = other.HubCategory;
          }
          if (other.HasHubTagid) {
            HubTagid = other.HubTagid;
          }
          if (other.HasDiscountFilter) {
            DiscountFilter = other.DiscountFilter;
          }
          if (other.optin_ != null) {
            if (optin_ == null) {
              Optin = new global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter.Types.OptInInfo();
            }
            Optin.MergeFrom(other.Optin);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                HubType = input.ReadString();
                break;
              }
              case 18: {
                HubCategory = input.ReadString();
                break;
              }
              case 24: {
                HubTagid = input.ReadUInt32();
                break;
              }
              case 32: {
                DiscountFilter = (global::OpenSteamworks.Protobuf.EContentHubDiscountFilterType) input.ReadEnum();
                break;
              }
              case 42: {
                if (optin_ == null) {
                  Optin = new global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter.Types.OptInInfo();
                }
                input.ReadMessage(Optin);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                HubType = input.ReadString();
                break;
              }
              case 18: {
                HubCategory = input.ReadString();
                break;
              }
              case 24: {
                HubTagid = input.ReadUInt32();
                break;
              }
              case 32: {
                DiscountFilter = (global::OpenSteamworks.Protobuf.EContentHubDiscountFilterType) input.ReadEnum();
                break;
              }
              case 42: {
                if (optin_ == null) {
                  Optin = new global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter.Types.OptInInfo();
                }
                input.ReadMessage(Optin);
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the ContentHubFilter message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class OptInInfo : pb::IMessage<OptInInfo>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<OptInInfo> _parser = new pb::MessageParser<OptInInfo>(() => new OptInInfo());
            private pb::UnknownFieldSet _unknownFields;
            private int _hasBits0;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<OptInInfo> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::OpenSteamworks.Protobuf.CStorePageFilter.Types.ContentHubFilter.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public OptInInfo() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public OptInInfo(OptInInfo other) : this() {
              _hasBits0 = other._hasBits0;
              name_ = other.name_;
              optinTagid_ = other.optinTagid_;
              pruneTagid_ = other.pruneTagid_;
              optinOnly_ = other.optinOnly_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public OptInInfo Clone() {
              return new OptInInfo(this);
            }

            /// <summary>Field number for the "name" field.</summary>
            public const int NameFieldNumber = 1;
            private readonly static string NameDefaultValue = "";

            private string name_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string Name {
              get { return name_ ?? NameDefaultValue; }
              set {
                name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }
            /// <summary>Gets whether the "name" field is set</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool HasName {
              get { return name_ != null; }
            }
            /// <summary>Clears the value of the "name" field</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void ClearName() {
              name_ = null;
            }

            /// <summary>Field number for the "optin_tagid" field.</summary>
            public const int OptinTagidFieldNumber = 2;
            private readonly static uint OptinTagidDefaultValue = 0;

            private uint optinTagid_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public uint OptinTagid {
              get { if ((_hasBits0 & 1) != 0) { return optinTagid_; } else { return OptinTagidDefaultValue; } }
              set {
                _hasBits0 |= 1;
                optinTagid_ = value;
              }
            }
            /// <summary>Gets whether the "optin_tagid" field is set</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool HasOptinTagid {
              get { return (_hasBits0 & 1) != 0; }
            }
            /// <summary>Clears the value of the "optin_tagid" field</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void ClearOptinTagid() {
              _hasBits0 &= ~1;
            }

            /// <summary>Field number for the "prune_tagid" field.</summary>
            public const int PruneTagidFieldNumber = 3;
            private readonly static uint PruneTagidDefaultValue = 0;

            private uint pruneTagid_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public uint PruneTagid {
              get { if ((_hasBits0 & 2) != 0) { return pruneTagid_; } else { return PruneTagidDefaultValue; } }
              set {
                _hasBits0 |= 2;
                pruneTagid_ = value;
              }
            }
            /// <summary>Gets whether the "prune_tagid" field is set</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool HasPruneTagid {
              get { return (_hasBits0 & 2) != 0; }
            }
            /// <summary>Clears the value of the "prune_tagid" field</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void ClearPruneTagid() {
              _hasBits0 &= ~2;
            }

            /// <summary>Field number for the "optin_only" field.</summary>
            public const int OptinOnlyFieldNumber = 4;
            private readonly static bool OptinOnlyDefaultValue = false;

            private bool optinOnly_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool OptinOnly {
              get { if ((_hasBits0 & 4) != 0) { return optinOnly_; } else { return OptinOnlyDefaultValue; } }
              set {
                _hasBits0 |= 4;
                optinOnly_ = value;
              }
            }
            /// <summary>Gets whether the "optin_only" field is set</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool HasOptinOnly {
              get { return (_hasBits0 & 4) != 0; }
            }
            /// <summary>Clears the value of the "optin_only" field</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void ClearOptinOnly() {
              _hasBits0 &= ~4;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as OptInInfo);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(OptInInfo other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Name != other.Name) return false;
              if (OptinTagid != other.OptinTagid) return false;
              if (PruneTagid != other.PruneTagid) return false;
              if (OptinOnly != other.OptinOnly) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (HasName) hash ^= Name.GetHashCode();
              if (HasOptinTagid) hash ^= OptinTagid.GetHashCode();
              if (HasPruneTagid) hash ^= PruneTagid.GetHashCode();
              if (HasOptinOnly) hash ^= OptinOnly.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (HasName) {
                output.WriteRawTag(10);
                output.WriteString(Name);
              }
              if (HasOptinTagid) {
                output.WriteRawTag(16);
                output.WriteUInt32(OptinTagid);
              }
              if (HasPruneTagid) {
                output.WriteRawTag(24);
                output.WriteUInt32(PruneTagid);
              }
              if (HasOptinOnly) {
                output.WriteRawTag(32);
                output.WriteBool(OptinOnly);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (HasName) {
                output.WriteRawTag(10);
                output.WriteString(Name);
              }
              if (HasOptinTagid) {
                output.WriteRawTag(16);
                output.WriteUInt32(OptinTagid);
              }
              if (HasPruneTagid) {
                output.WriteRawTag(24);
                output.WriteUInt32(PruneTagid);
              }
              if (HasOptinOnly) {
                output.WriteRawTag(32);
                output.WriteBool(OptinOnly);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (HasName) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
              }
              if (HasOptinTagid) {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OptinTagid);
              }
              if (HasPruneTagid) {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PruneTagid);
              }
              if (HasOptinOnly) {
                size += 1 + 1;
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(OptInInfo other) {
              if (other == null) {
                return;
              }
              if (other.HasName) {
                Name = other.Name;
              }
              if (other.HasOptinTagid) {
                OptinTagid = other.OptinTagid;
              }
              if (other.HasPruneTagid) {
                PruneTagid = other.PruneTagid;
              }
              if (other.HasOptinOnly) {
                OptinOnly = other.OptinOnly;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    Name = input.ReadString();
                    break;
                  }
                  case 16: {
                    OptinTagid = input.ReadUInt32();
                    break;
                  }
                  case 24: {
                    PruneTagid = input.ReadUInt32();
                    break;
                  }
                  case 32: {
                    OptinOnly = input.ReadBool();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 10: {
                    Name = input.ReadString();
                    break;
                  }
                  case 16: {
                    OptinTagid = input.ReadUInt32();
                    break;
                  }
                  case 24: {
                    PruneTagid = input.ReadUInt32();
                    break;
                  }
                  case 32: {
                    OptinOnly = input.ReadBool();
                    break;
                  }
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class StoreFilter : pb::IMessage<StoreFilter>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<StoreFilter> _parser = new pb::MessageParser<StoreFilter>(() => new StoreFilter());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<StoreFilter> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::OpenSteamworks.Protobuf.CStorePageFilter.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public StoreFilter() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public StoreFilter(StoreFilter other) : this() {
          filterJson_ = other.filterJson_;
          cacheKey_ = other.cacheKey_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public StoreFilter Clone() {
          return new StoreFilter(this);
        }

        /// <summary>Field number for the "filter_json" field.</summary>
        public const int FilterJsonFieldNumber = 1;
        private readonly static string FilterJsonDefaultValue = "";

        private string filterJson_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string FilterJson {
          get { return filterJson_ ?? FilterJsonDefaultValue; }
          set {
            filterJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "filter_json" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasFilterJson {
          get { return filterJson_ != null; }
        }
        /// <summary>Clears the value of the "filter_json" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearFilterJson() {
          filterJson_ = null;
        }

        /// <summary>Field number for the "cache_key" field.</summary>
        public const int CacheKeyFieldNumber = 2;
        private readonly static string CacheKeyDefaultValue = "";

        private string cacheKey_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string CacheKey {
          get { return cacheKey_ ?? CacheKeyDefaultValue; }
          set {
            cacheKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "cache_key" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasCacheKey {
          get { return cacheKey_ != null; }
        }
        /// <summary>Clears the value of the "cache_key" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearCacheKey() {
          cacheKey_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as StoreFilter);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(StoreFilter other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (FilterJson != other.FilterJson) return false;
          if (CacheKey != other.CacheKey) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasFilterJson) hash ^= FilterJson.GetHashCode();
          if (HasCacheKey) hash ^= CacheKey.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasFilterJson) {
            output.WriteRawTag(10);
            output.WriteString(FilterJson);
          }
          if (HasCacheKey) {
            output.WriteRawTag(18);
            output.WriteString(CacheKey);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasFilterJson) {
            output.WriteRawTag(10);
            output.WriteString(FilterJson);
          }
          if (HasCacheKey) {
            output.WriteRawTag(18);
            output.WriteString(CacheKey);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasFilterJson) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(FilterJson);
          }
          if (HasCacheKey) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(CacheKey);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(StoreFilter other) {
          if (other == null) {
            return;
          }
          if (other.HasFilterJson) {
            FilterJson = other.FilterJson;
          }
          if (other.HasCacheKey) {
            CacheKey = other.CacheKey;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                FilterJson = input.ReadString();
                break;
              }
              case 18: {
                CacheKey = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                FilterJson = input.ReadString();
                break;
              }
              case 18: {
                CacheKey = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
