// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service_partnermembershipinvite.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenSteamworks.Protobuf.WebUI {

  /// <summary>Holder for reflection information generated from service_partnermembershipinvite.proto</summary>
  public static partial class ServicePartnermembershipinviteReflection {

    #region Descriptor
    /// <summary>File descriptor for service_partnermembershipinvite.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicePartnermembershipinviteReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVzZXJ2aWNlX3BhcnRuZXJtZW1iZXJzaGlwaW52aXRlLnByb3RvGiBnb29n",
            "bGUvcHJvdG9idWYvZGVzY3JpcHRvci5wcm90bxoRY29tbW9uX2Jhc2UucHJv",
            "dG8iYQorQ1BhcnRuZXJNZW1iZXJzaGlwSW52aXRlX0dldEludml0ZXNfUmVx",
            "dWVzdBIRCglwYXJ0bmVyaWQYASABKA0SHwoNZmlsdGVyX3N0YXRlcxgCIAMo",
            "BUIIgrUYBGVudW0iUgosQ1BhcnRuZXJNZW1iZXJzaGlwSW52aXRlX0dldElu",
            "dml0ZXNfUmVzcG9uc2USIgoHaW52aXRlcxgBIAMoCzIRLk1lbWJlcnNoaXBJ",
            "bnZpdGUi+gIKEE1lbWJlcnNoaXBJbnZpdGUSEAoIaW52aXRlaWQYASABKAQS",
            "GAoQYWNjb3VudGlkX3NlbmRlchgCIAEoDRINCgVlbWFpbBgDIAEoCRIRCgly",
            "ZWFsX25hbWUYBCABKAkSDAoEbm90ZRgFIAEoCRIRCgl0aW1lX3NlbnQYBiAB",
            "KA0SHwoNY3VycmVudF9zdGF0ZRgHIAEoBUIIgrUYBGVudW0SEgoKcHViX3Jp",
            "Z2h0cxgIIAEoBBISCgphcHBfcmlnaHRzGAkgASgEEh8KF3RpbWVfcmVjZWl2",
            "ZXJfcmVzcG9uZGVkGAogASgNEhEKCWFjY291bnRpZBgLIAEoDRIeChZ0aW1l",
            "X3BhcnRuZXJfcmVzcG9uZGVkGAwgASgNEhkKEWFjY291bnRpZF9wYXJ0bmVy",
            "GA0gASgNEhEKCXBhcnRuZXJpZBgOIAEoDRIZChF0aW1lX2xhc3RfdXBkYXRl",
            "ZBgPIAEoDRIRCglzZW5kZXJfaXAYECABKAkyhAEKF1BhcnRuZXJNZW1iZXJz",
            "aGlwSW52aXRlEmkKCkdldEludml0ZXMSLC5DUGFydG5lck1lbWJlcnNoaXBJ",
            "bnZpdGVfR2V0SW52aXRlc19SZXF1ZXN0Gi0uQ1BhcnRuZXJNZW1iZXJzaGlw",
            "SW52aXRlX0dldEludml0ZXNfUmVzcG9uc2VCIKoCHU9wZW5TdGVhbXdvcmtz",
            "LlByb3RvYnVmLldlYlVJ"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, global::OpenSteamworks.Protobuf.WebUI.CommonBaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerMembershipInvite_GetInvites_Request), global::OpenSteamworks.Protobuf.WebUI.CPartnerMembershipInvite_GetInvites_Request.Parser, new[]{ "Partnerid", "FilterStates" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CPartnerMembershipInvite_GetInvites_Response), global::OpenSteamworks.Protobuf.WebUI.CPartnerMembershipInvite_GetInvites_Response.Parser, new[]{ "Invites" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.MembershipInvite), global::OpenSteamworks.Protobuf.WebUI.MembershipInvite.Parser, new[]{ "Inviteid", "AccountidSender", "Email", "RealName", "Note", "TimeSent", "CurrentState", "PubRights", "AppRights", "TimeReceiverResponded", "Accountid", "TimePartnerResponded", "AccountidPartner", "Partnerid", "TimeLastUpdated", "SenderIp" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerMembershipInvite_GetInvites_Request : pb::IMessage<CPartnerMembershipInvite_GetInvites_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerMembershipInvite_GetInvites_Request> _parser = new pb::MessageParser<CPartnerMembershipInvite_GetInvites_Request>(() => new CPartnerMembershipInvite_GetInvites_Request());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerMembershipInvite_GetInvites_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnermembershipinviteReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerMembershipInvite_GetInvites_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerMembershipInvite_GetInvites_Request(CPartnerMembershipInvite_GetInvites_Request other) : this() {
      _hasBits0 = other._hasBits0;
      partnerid_ = other.partnerid_;
      filterStates_ = other.filterStates_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerMembershipInvite_GetInvites_Request Clone() {
      return new CPartnerMembershipInvite_GetInvites_Request(this);
    }

    /// <summary>Field number for the "partnerid" field.</summary>
    public const int PartneridFieldNumber = 1;
    private readonly static uint PartneridDefaultValue = 0;

    private uint partnerid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Partnerid {
      get { if ((_hasBits0 & 1) != 0) { return partnerid_; } else { return PartneridDefaultValue; } }
      set {
        _hasBits0 |= 1;
        partnerid_ = value;
      }
    }
    /// <summary>Gets whether the "partnerid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPartnerid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "partnerid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPartnerid() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "filter_states" field.</summary>
    public const int FilterStatesFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_filterStates_codec
        = pb::FieldCodec.ForInt32(16);
    private readonly pbc::RepeatedField<int> filterStates_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> FilterStates {
      get { return filterStates_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerMembershipInvite_GetInvites_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerMembershipInvite_GetInvites_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Partnerid != other.Partnerid) return false;
      if(!filterStates_.Equals(other.filterStates_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPartnerid) hash ^= Partnerid.GetHashCode();
      hash ^= filterStates_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPartnerid) {
        output.WriteRawTag(8);
        output.WriteUInt32(Partnerid);
      }
      filterStates_.WriteTo(output, _repeated_filterStates_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPartnerid) {
        output.WriteRawTag(8);
        output.WriteUInt32(Partnerid);
      }
      filterStates_.WriteTo(ref output, _repeated_filterStates_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPartnerid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Partnerid);
      }
      size += filterStates_.CalculateSize(_repeated_filterStates_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerMembershipInvite_GetInvites_Request other) {
      if (other == null) {
        return;
      }
      if (other.HasPartnerid) {
        Partnerid = other.Partnerid;
      }
      filterStates_.Add(other.filterStates_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 18:
          case 16: {
            filterStates_.AddEntriesFrom(input, _repeated_filterStates_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 18:
          case 16: {
            filterStates_.AddEntriesFrom(ref input, _repeated_filterStates_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CPartnerMembershipInvite_GetInvites_Response : pb::IMessage<CPartnerMembershipInvite_GetInvites_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CPartnerMembershipInvite_GetInvites_Response> _parser = new pb::MessageParser<CPartnerMembershipInvite_GetInvites_Response>(() => new CPartnerMembershipInvite_GetInvites_Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CPartnerMembershipInvite_GetInvites_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnermembershipinviteReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerMembershipInvite_GetInvites_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerMembershipInvite_GetInvites_Response(CPartnerMembershipInvite_GetInvites_Response other) : this() {
      invites_ = other.invites_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CPartnerMembershipInvite_GetInvites_Response Clone() {
      return new CPartnerMembershipInvite_GetInvites_Response(this);
    }

    /// <summary>Field number for the "invites" field.</summary>
    public const int InvitesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::OpenSteamworks.Protobuf.WebUI.MembershipInvite> _repeated_invites_codec
        = pb::FieldCodec.ForMessage(10, global::OpenSteamworks.Protobuf.WebUI.MembershipInvite.Parser);
    private readonly pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.MembershipInvite> invites_ = new pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.MembershipInvite>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenSteamworks.Protobuf.WebUI.MembershipInvite> Invites {
      get { return invites_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CPartnerMembershipInvite_GetInvites_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CPartnerMembershipInvite_GetInvites_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!invites_.Equals(other.invites_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= invites_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      invites_.WriteTo(output, _repeated_invites_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      invites_.WriteTo(ref output, _repeated_invites_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += invites_.CalculateSize(_repeated_invites_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CPartnerMembershipInvite_GetInvites_Response other) {
      if (other == null) {
        return;
      }
      invites_.Add(other.invites_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            invites_.AddEntriesFrom(input, _repeated_invites_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            invites_.AddEntriesFrom(ref input, _repeated_invites_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MembershipInvite : pb::IMessage<MembershipInvite>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MembershipInvite> _parser = new pb::MessageParser<MembershipInvite>(() => new MembershipInvite());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MembershipInvite> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServicePartnermembershipinviteReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MembershipInvite() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MembershipInvite(MembershipInvite other) : this() {
      _hasBits0 = other._hasBits0;
      inviteid_ = other.inviteid_;
      accountidSender_ = other.accountidSender_;
      email_ = other.email_;
      realName_ = other.realName_;
      note_ = other.note_;
      timeSent_ = other.timeSent_;
      currentState_ = other.currentState_;
      pubRights_ = other.pubRights_;
      appRights_ = other.appRights_;
      timeReceiverResponded_ = other.timeReceiverResponded_;
      accountid_ = other.accountid_;
      timePartnerResponded_ = other.timePartnerResponded_;
      accountidPartner_ = other.accountidPartner_;
      partnerid_ = other.partnerid_;
      timeLastUpdated_ = other.timeLastUpdated_;
      senderIp_ = other.senderIp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MembershipInvite Clone() {
      return new MembershipInvite(this);
    }

    /// <summary>Field number for the "inviteid" field.</summary>
    public const int InviteidFieldNumber = 1;
    private readonly static ulong InviteidDefaultValue = 0UL;

    private ulong inviteid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Inviteid {
      get { if ((_hasBits0 & 1) != 0) { return inviteid_; } else { return InviteidDefaultValue; } }
      set {
        _hasBits0 |= 1;
        inviteid_ = value;
      }
    }
    /// <summary>Gets whether the "inviteid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasInviteid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "inviteid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInviteid() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "accountid_sender" field.</summary>
    public const int AccountidSenderFieldNumber = 2;
    private readonly static uint AccountidSenderDefaultValue = 0;

    private uint accountidSender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AccountidSender {
      get { if ((_hasBits0 & 2) != 0) { return accountidSender_; } else { return AccountidSenderDefaultValue; } }
      set {
        _hasBits0 |= 2;
        accountidSender_ = value;
      }
    }
    /// <summary>Gets whether the "accountid_sender" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAccountidSender {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "accountid_sender" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAccountidSender() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 3;
    private readonly static string EmailDefaultValue = "";

    private string email_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_ ?? EmailDefaultValue; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "email" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEmail {
      get { return email_ != null; }
    }
    /// <summary>Clears the value of the "email" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEmail() {
      email_ = null;
    }

    /// <summary>Field number for the "real_name" field.</summary>
    public const int RealNameFieldNumber = 4;
    private readonly static string RealNameDefaultValue = "";

    private string realName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RealName {
      get { return realName_ ?? RealNameDefaultValue; }
      set {
        realName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "real_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRealName {
      get { return realName_ != null; }
    }
    /// <summary>Clears the value of the "real_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRealName() {
      realName_ = null;
    }

    /// <summary>Field number for the "note" field.</summary>
    public const int NoteFieldNumber = 5;
    private readonly static string NoteDefaultValue = "";

    private string note_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Note {
      get { return note_ ?? NoteDefaultValue; }
      set {
        note_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "note" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNote {
      get { return note_ != null; }
    }
    /// <summary>Clears the value of the "note" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNote() {
      note_ = null;
    }

    /// <summary>Field number for the "time_sent" field.</summary>
    public const int TimeSentFieldNumber = 6;
    private readonly static uint TimeSentDefaultValue = 0;

    private uint timeSent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimeSent {
      get { if ((_hasBits0 & 4) != 0) { return timeSent_; } else { return TimeSentDefaultValue; } }
      set {
        _hasBits0 |= 4;
        timeSent_ = value;
      }
    }
    /// <summary>Gets whether the "time_sent" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTimeSent {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "time_sent" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTimeSent() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "current_state" field.</summary>
    public const int CurrentStateFieldNumber = 7;
    private readonly static int CurrentStateDefaultValue = 0;

    private int currentState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurrentState {
      get { if ((_hasBits0 & 8) != 0) { return currentState_; } else { return CurrentStateDefaultValue; } }
      set {
        _hasBits0 |= 8;
        currentState_ = value;
      }
    }
    /// <summary>Gets whether the "current_state" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCurrentState {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "current_state" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCurrentState() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "pub_rights" field.</summary>
    public const int PubRightsFieldNumber = 8;
    private readonly static ulong PubRightsDefaultValue = 0UL;

    private ulong pubRights_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PubRights {
      get { if ((_hasBits0 & 16) != 0) { return pubRights_; } else { return PubRightsDefaultValue; } }
      set {
        _hasBits0 |= 16;
        pubRights_ = value;
      }
    }
    /// <summary>Gets whether the "pub_rights" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPubRights {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "pub_rights" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPubRights() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "app_rights" field.</summary>
    public const int AppRightsFieldNumber = 9;
    private readonly static ulong AppRightsDefaultValue = 0UL;

    private ulong appRights_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong AppRights {
      get { if ((_hasBits0 & 32) != 0) { return appRights_; } else { return AppRightsDefaultValue; } }
      set {
        _hasBits0 |= 32;
        appRights_ = value;
      }
    }
    /// <summary>Gets whether the "app_rights" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAppRights {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "app_rights" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAppRights() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "time_receiver_responded" field.</summary>
    public const int TimeReceiverRespondedFieldNumber = 10;
    private readonly static uint TimeReceiverRespondedDefaultValue = 0;

    private uint timeReceiverResponded_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimeReceiverResponded {
      get { if ((_hasBits0 & 64) != 0) { return timeReceiverResponded_; } else { return TimeReceiverRespondedDefaultValue; } }
      set {
        _hasBits0 |= 64;
        timeReceiverResponded_ = value;
      }
    }
    /// <summary>Gets whether the "time_receiver_responded" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTimeReceiverResponded {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "time_receiver_responded" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTimeReceiverResponded() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "accountid" field.</summary>
    public const int AccountidFieldNumber = 11;
    private readonly static uint AccountidDefaultValue = 0;

    private uint accountid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Accountid {
      get { if ((_hasBits0 & 128) != 0) { return accountid_; } else { return AccountidDefaultValue; } }
      set {
        _hasBits0 |= 128;
        accountid_ = value;
      }
    }
    /// <summary>Gets whether the "accountid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAccountid {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "accountid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAccountid() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "time_partner_responded" field.</summary>
    public const int TimePartnerRespondedFieldNumber = 12;
    private readonly static uint TimePartnerRespondedDefaultValue = 0;

    private uint timePartnerResponded_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimePartnerResponded {
      get { if ((_hasBits0 & 256) != 0) { return timePartnerResponded_; } else { return TimePartnerRespondedDefaultValue; } }
      set {
        _hasBits0 |= 256;
        timePartnerResponded_ = value;
      }
    }
    /// <summary>Gets whether the "time_partner_responded" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTimePartnerResponded {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "time_partner_responded" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTimePartnerResponded() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "accountid_partner" field.</summary>
    public const int AccountidPartnerFieldNumber = 13;
    private readonly static uint AccountidPartnerDefaultValue = 0;

    private uint accountidPartner_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AccountidPartner {
      get { if ((_hasBits0 & 512) != 0) { return accountidPartner_; } else { return AccountidPartnerDefaultValue; } }
      set {
        _hasBits0 |= 512;
        accountidPartner_ = value;
      }
    }
    /// <summary>Gets whether the "accountid_partner" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAccountidPartner {
      get { return (_hasBits0 & 512) != 0; }
    }
    /// <summary>Clears the value of the "accountid_partner" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAccountidPartner() {
      _hasBits0 &= ~512;
    }

    /// <summary>Field number for the "partnerid" field.</summary>
    public const int PartneridFieldNumber = 14;
    private readonly static uint PartneridDefaultValue = 0;

    private uint partnerid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Partnerid {
      get { if ((_hasBits0 & 1024) != 0) { return partnerid_; } else { return PartneridDefaultValue; } }
      set {
        _hasBits0 |= 1024;
        partnerid_ = value;
      }
    }
    /// <summary>Gets whether the "partnerid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPartnerid {
      get { return (_hasBits0 & 1024) != 0; }
    }
    /// <summary>Clears the value of the "partnerid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPartnerid() {
      _hasBits0 &= ~1024;
    }

    /// <summary>Field number for the "time_last_updated" field.</summary>
    public const int TimeLastUpdatedFieldNumber = 15;
    private readonly static uint TimeLastUpdatedDefaultValue = 0;

    private uint timeLastUpdated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimeLastUpdated {
      get { if ((_hasBits0 & 2048) != 0) { return timeLastUpdated_; } else { return TimeLastUpdatedDefaultValue; } }
      set {
        _hasBits0 |= 2048;
        timeLastUpdated_ = value;
      }
    }
    /// <summary>Gets whether the "time_last_updated" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTimeLastUpdated {
      get { return (_hasBits0 & 2048) != 0; }
    }
    /// <summary>Clears the value of the "time_last_updated" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTimeLastUpdated() {
      _hasBits0 &= ~2048;
    }

    /// <summary>Field number for the "sender_ip" field.</summary>
    public const int SenderIpFieldNumber = 16;
    private readonly static string SenderIpDefaultValue = "";

    private string senderIp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderIp {
      get { return senderIp_ ?? SenderIpDefaultValue; }
      set {
        senderIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "sender_ip" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSenderIp {
      get { return senderIp_ != null; }
    }
    /// <summary>Clears the value of the "sender_ip" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSenderIp() {
      senderIp_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MembershipInvite);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MembershipInvite other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Inviteid != other.Inviteid) return false;
      if (AccountidSender != other.AccountidSender) return false;
      if (Email != other.Email) return false;
      if (RealName != other.RealName) return false;
      if (Note != other.Note) return false;
      if (TimeSent != other.TimeSent) return false;
      if (CurrentState != other.CurrentState) return false;
      if (PubRights != other.PubRights) return false;
      if (AppRights != other.AppRights) return false;
      if (TimeReceiverResponded != other.TimeReceiverResponded) return false;
      if (Accountid != other.Accountid) return false;
      if (TimePartnerResponded != other.TimePartnerResponded) return false;
      if (AccountidPartner != other.AccountidPartner) return false;
      if (Partnerid != other.Partnerid) return false;
      if (TimeLastUpdated != other.TimeLastUpdated) return false;
      if (SenderIp != other.SenderIp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasInviteid) hash ^= Inviteid.GetHashCode();
      if (HasAccountidSender) hash ^= AccountidSender.GetHashCode();
      if (HasEmail) hash ^= Email.GetHashCode();
      if (HasRealName) hash ^= RealName.GetHashCode();
      if (HasNote) hash ^= Note.GetHashCode();
      if (HasTimeSent) hash ^= TimeSent.GetHashCode();
      if (HasCurrentState) hash ^= CurrentState.GetHashCode();
      if (HasPubRights) hash ^= PubRights.GetHashCode();
      if (HasAppRights) hash ^= AppRights.GetHashCode();
      if (HasTimeReceiverResponded) hash ^= TimeReceiverResponded.GetHashCode();
      if (HasAccountid) hash ^= Accountid.GetHashCode();
      if (HasTimePartnerResponded) hash ^= TimePartnerResponded.GetHashCode();
      if (HasAccountidPartner) hash ^= AccountidPartner.GetHashCode();
      if (HasPartnerid) hash ^= Partnerid.GetHashCode();
      if (HasTimeLastUpdated) hash ^= TimeLastUpdated.GetHashCode();
      if (HasSenderIp) hash ^= SenderIp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasInviteid) {
        output.WriteRawTag(8);
        output.WriteUInt64(Inviteid);
      }
      if (HasAccountidSender) {
        output.WriteRawTag(16);
        output.WriteUInt32(AccountidSender);
      }
      if (HasEmail) {
        output.WriteRawTag(26);
        output.WriteString(Email);
      }
      if (HasRealName) {
        output.WriteRawTag(34);
        output.WriteString(RealName);
      }
      if (HasNote) {
        output.WriteRawTag(42);
        output.WriteString(Note);
      }
      if (HasTimeSent) {
        output.WriteRawTag(48);
        output.WriteUInt32(TimeSent);
      }
      if (HasCurrentState) {
        output.WriteRawTag(56);
        output.WriteInt32(CurrentState);
      }
      if (HasPubRights) {
        output.WriteRawTag(64);
        output.WriteUInt64(PubRights);
      }
      if (HasAppRights) {
        output.WriteRawTag(72);
        output.WriteUInt64(AppRights);
      }
      if (HasTimeReceiverResponded) {
        output.WriteRawTag(80);
        output.WriteUInt32(TimeReceiverResponded);
      }
      if (HasAccountid) {
        output.WriteRawTag(88);
        output.WriteUInt32(Accountid);
      }
      if (HasTimePartnerResponded) {
        output.WriteRawTag(96);
        output.WriteUInt32(TimePartnerResponded);
      }
      if (HasAccountidPartner) {
        output.WriteRawTag(104);
        output.WriteUInt32(AccountidPartner);
      }
      if (HasPartnerid) {
        output.WriteRawTag(112);
        output.WriteUInt32(Partnerid);
      }
      if (HasTimeLastUpdated) {
        output.WriteRawTag(120);
        output.WriteUInt32(TimeLastUpdated);
      }
      if (HasSenderIp) {
        output.WriteRawTag(130, 1);
        output.WriteString(SenderIp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasInviteid) {
        output.WriteRawTag(8);
        output.WriteUInt64(Inviteid);
      }
      if (HasAccountidSender) {
        output.WriteRawTag(16);
        output.WriteUInt32(AccountidSender);
      }
      if (HasEmail) {
        output.WriteRawTag(26);
        output.WriteString(Email);
      }
      if (HasRealName) {
        output.WriteRawTag(34);
        output.WriteString(RealName);
      }
      if (HasNote) {
        output.WriteRawTag(42);
        output.WriteString(Note);
      }
      if (HasTimeSent) {
        output.WriteRawTag(48);
        output.WriteUInt32(TimeSent);
      }
      if (HasCurrentState) {
        output.WriteRawTag(56);
        output.WriteInt32(CurrentState);
      }
      if (HasPubRights) {
        output.WriteRawTag(64);
        output.WriteUInt64(PubRights);
      }
      if (HasAppRights) {
        output.WriteRawTag(72);
        output.WriteUInt64(AppRights);
      }
      if (HasTimeReceiverResponded) {
        output.WriteRawTag(80);
        output.WriteUInt32(TimeReceiverResponded);
      }
      if (HasAccountid) {
        output.WriteRawTag(88);
        output.WriteUInt32(Accountid);
      }
      if (HasTimePartnerResponded) {
        output.WriteRawTag(96);
        output.WriteUInt32(TimePartnerResponded);
      }
      if (HasAccountidPartner) {
        output.WriteRawTag(104);
        output.WriteUInt32(AccountidPartner);
      }
      if (HasPartnerid) {
        output.WriteRawTag(112);
        output.WriteUInt32(Partnerid);
      }
      if (HasTimeLastUpdated) {
        output.WriteRawTag(120);
        output.WriteUInt32(TimeLastUpdated);
      }
      if (HasSenderIp) {
        output.WriteRawTag(130, 1);
        output.WriteString(SenderIp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasInviteid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Inviteid);
      }
      if (HasAccountidSender) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AccountidSender);
      }
      if (HasEmail) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (HasRealName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RealName);
      }
      if (HasNote) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Note);
      }
      if (HasTimeSent) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimeSent);
      }
      if (HasCurrentState) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentState);
      }
      if (HasPubRights) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PubRights);
      }
      if (HasAppRights) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AppRights);
      }
      if (HasTimeReceiverResponded) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimeReceiverResponded);
      }
      if (HasAccountid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Accountid);
      }
      if (HasTimePartnerResponded) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimePartnerResponded);
      }
      if (HasAccountidPartner) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AccountidPartner);
      }
      if (HasPartnerid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Partnerid);
      }
      if (HasTimeLastUpdated) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimeLastUpdated);
      }
      if (HasSenderIp) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SenderIp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MembershipInvite other) {
      if (other == null) {
        return;
      }
      if (other.HasInviteid) {
        Inviteid = other.Inviteid;
      }
      if (other.HasAccountidSender) {
        AccountidSender = other.AccountidSender;
      }
      if (other.HasEmail) {
        Email = other.Email;
      }
      if (other.HasRealName) {
        RealName = other.RealName;
      }
      if (other.HasNote) {
        Note = other.Note;
      }
      if (other.HasTimeSent) {
        TimeSent = other.TimeSent;
      }
      if (other.HasCurrentState) {
        CurrentState = other.CurrentState;
      }
      if (other.HasPubRights) {
        PubRights = other.PubRights;
      }
      if (other.HasAppRights) {
        AppRights = other.AppRights;
      }
      if (other.HasTimeReceiverResponded) {
        TimeReceiverResponded = other.TimeReceiverResponded;
      }
      if (other.HasAccountid) {
        Accountid = other.Accountid;
      }
      if (other.HasTimePartnerResponded) {
        TimePartnerResponded = other.TimePartnerResponded;
      }
      if (other.HasAccountidPartner) {
        AccountidPartner = other.AccountidPartner;
      }
      if (other.HasPartnerid) {
        Partnerid = other.Partnerid;
      }
      if (other.HasTimeLastUpdated) {
        TimeLastUpdated = other.TimeLastUpdated;
      }
      if (other.HasSenderIp) {
        SenderIp = other.SenderIp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Inviteid = input.ReadUInt64();
            break;
          }
          case 16: {
            AccountidSender = input.ReadUInt32();
            break;
          }
          case 26: {
            Email = input.ReadString();
            break;
          }
          case 34: {
            RealName = input.ReadString();
            break;
          }
          case 42: {
            Note = input.ReadString();
            break;
          }
          case 48: {
            TimeSent = input.ReadUInt32();
            break;
          }
          case 56: {
            CurrentState = input.ReadInt32();
            break;
          }
          case 64: {
            PubRights = input.ReadUInt64();
            break;
          }
          case 72: {
            AppRights = input.ReadUInt64();
            break;
          }
          case 80: {
            TimeReceiverResponded = input.ReadUInt32();
            break;
          }
          case 88: {
            Accountid = input.ReadUInt32();
            break;
          }
          case 96: {
            TimePartnerResponded = input.ReadUInt32();
            break;
          }
          case 104: {
            AccountidPartner = input.ReadUInt32();
            break;
          }
          case 112: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 120: {
            TimeLastUpdated = input.ReadUInt32();
            break;
          }
          case 130: {
            SenderIp = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Inviteid = input.ReadUInt64();
            break;
          }
          case 16: {
            AccountidSender = input.ReadUInt32();
            break;
          }
          case 26: {
            Email = input.ReadString();
            break;
          }
          case 34: {
            RealName = input.ReadString();
            break;
          }
          case 42: {
            Note = input.ReadString();
            break;
          }
          case 48: {
            TimeSent = input.ReadUInt32();
            break;
          }
          case 56: {
            CurrentState = input.ReadInt32();
            break;
          }
          case 64: {
            PubRights = input.ReadUInt64();
            break;
          }
          case 72: {
            AppRights = input.ReadUInt64();
            break;
          }
          case 80: {
            TimeReceiverResponded = input.ReadUInt32();
            break;
          }
          case 88: {
            Accountid = input.ReadUInt32();
            break;
          }
          case 96: {
            TimePartnerResponded = input.ReadUInt32();
            break;
          }
          case 104: {
            AccountidPartner = input.ReadUInt32();
            break;
          }
          case 112: {
            Partnerid = input.ReadUInt32();
            break;
          }
          case 120: {
            TimeLastUpdated = input.ReadUInt32();
            break;
          }
          case 130: {
            SenderIp = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
