// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service_mobileperaccount.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenSteamworks.Protobuf.WebUI {

  /// <summary>Holder for reflection information generated from service_mobileperaccount.proto</summary>
  public static partial class ServiceMobileperaccountReflection {

    #region Descriptor
    /// <summary>File descriptor for service_mobileperaccount.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceMobileperaccountReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5zZXJ2aWNlX21vYmlsZXBlcmFjY291bnQucHJvdG8aIGdvb2dsZS9wcm90",
            "b2J1Zi9kZXNjcmlwdG9yLnByb3RvIicKJUNNb2JpbGVQZXJBY2NvdW50X0dl",
            "dFNldHRpbmdzX1JlcXVlc3Qi7AEKJkNNb2JpbGVQZXJBY2NvdW50X0dldFNl",
            "dHRpbmdzX1Jlc3BvbnNlEhcKD2FsbG93X3NhbGVfcHVzaBgCIAEoCBIbChNh",
            "bGxvd193aXNobGlzdF9wdXNoGAMgASgIEhQKDGhhc19zZXR0aW5ncxgEIAEo",
            "CBIfChdjaGF0X25vdGlmaWNhdGlvbl9sZXZlbBgFIAEoDRIaChJub3RpZnlf",
            "ZGlyZWN0X2NoYXQYBiABKAgSGQoRbm90aWZ5X2dyb3VwX2NoYXQYByABKAgS",
            "HgoQYWxsb3dfZXZlbnRfcHVzaBgIIAEoCDoEdHJ1ZSLVAQolQ01vYmlsZVBl",
            "ckFjY291bnRfU2V0U2V0dGluZ3NfUmVxdWVzdBIXCg9hbGxvd19zYWxlX3B1",
            "c2gYAiABKAgSGwoTYWxsb3dfd2lzaGxpc3RfcHVzaBgDIAEoCBIfChdjaGF0",
            "X25vdGlmaWNhdGlvbl9sZXZlbBgEIAEoDRIaChJub3RpZnlfZGlyZWN0X2No",
            "YXQYBSABKAgSGQoRbm90aWZ5X2dyb3VwX2NoYXQYBiABKAgSHgoQYWxsb3df",
            "ZXZlbnRfcHVzaBgHIAEoCDoEdHJ1ZSIoCiZDTW9iaWxlUGVyQWNjb3VudF9T",
            "ZXRTZXR0aW5nc19SZXNwb25zZTLSAQoQTW9iaWxlUGVyQWNjb3VudBJeCgtH",
            "ZXRTZXR0aW5ncxImLkNNb2JpbGVQZXJBY2NvdW50X0dldFNldHRpbmdzX1Jl",
            "cXVlc3QaJy5DTW9iaWxlUGVyQWNjb3VudF9HZXRTZXR0aW5nc19SZXNwb25z",
            "ZRJeCgtTZXRTZXR0aW5ncxImLkNNb2JpbGVQZXJBY2NvdW50X1NldFNldHRp",
            "bmdzX1JlcXVlc3QaJy5DTW9iaWxlUGVyQWNjb3VudF9TZXRTZXR0aW5nc19S",
            "ZXNwb25zZUIgqgIdT3BlblN0ZWFtd29ya3MuUHJvdG9idWYuV2ViVUk="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CMobilePerAccount_GetSettings_Request), global::OpenSteamworks.Protobuf.WebUI.CMobilePerAccount_GetSettings_Request.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CMobilePerAccount_GetSettings_Response), global::OpenSteamworks.Protobuf.WebUI.CMobilePerAccount_GetSettings_Response.Parser, new[]{ "AllowSalePush", "AllowWishlistPush", "HasSettings", "ChatNotificationLevel", "NotifyDirectChat", "NotifyGroupChat", "AllowEventPush" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CMobilePerAccount_SetSettings_Request), global::OpenSteamworks.Protobuf.WebUI.CMobilePerAccount_SetSettings_Request.Parser, new[]{ "AllowSalePush", "AllowWishlistPush", "ChatNotificationLevel", "NotifyDirectChat", "NotifyGroupChat", "AllowEventPush" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenSteamworks.Protobuf.WebUI.CMobilePerAccount_SetSettings_Response), global::OpenSteamworks.Protobuf.WebUI.CMobilePerAccount_SetSettings_Response.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CMobilePerAccount_GetSettings_Request : pb::IMessage<CMobilePerAccount_GetSettings_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CMobilePerAccount_GetSettings_Request> _parser = new pb::MessageParser<CMobilePerAccount_GetSettings_Request>(() => new CMobilePerAccount_GetSettings_Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CMobilePerAccount_GetSettings_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServiceMobileperaccountReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_GetSettings_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_GetSettings_Request(CMobilePerAccount_GetSettings_Request other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_GetSettings_Request Clone() {
      return new CMobilePerAccount_GetSettings_Request(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CMobilePerAccount_GetSettings_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CMobilePerAccount_GetSettings_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CMobilePerAccount_GetSettings_Request other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CMobilePerAccount_GetSettings_Response : pb::IMessage<CMobilePerAccount_GetSettings_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CMobilePerAccount_GetSettings_Response> _parser = new pb::MessageParser<CMobilePerAccount_GetSettings_Response>(() => new CMobilePerAccount_GetSettings_Response());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CMobilePerAccount_GetSettings_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServiceMobileperaccountReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_GetSettings_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_GetSettings_Response(CMobilePerAccount_GetSettings_Response other) : this() {
      _hasBits0 = other._hasBits0;
      allowSalePush_ = other.allowSalePush_;
      allowWishlistPush_ = other.allowWishlistPush_;
      hasSettings_ = other.hasSettings_;
      chatNotificationLevel_ = other.chatNotificationLevel_;
      notifyDirectChat_ = other.notifyDirectChat_;
      notifyGroupChat_ = other.notifyGroupChat_;
      allowEventPush_ = other.allowEventPush_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_GetSettings_Response Clone() {
      return new CMobilePerAccount_GetSettings_Response(this);
    }

    /// <summary>Field number for the "allow_sale_push" field.</summary>
    public const int AllowSalePushFieldNumber = 2;
    private readonly static bool AllowSalePushDefaultValue = false;

    private bool allowSalePush_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AllowSalePush {
      get { if ((_hasBits0 & 1) != 0) { return allowSalePush_; } else { return AllowSalePushDefaultValue; } }
      set {
        _hasBits0 |= 1;
        allowSalePush_ = value;
      }
    }
    /// <summary>Gets whether the "allow_sale_push" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAllowSalePush {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "allow_sale_push" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAllowSalePush() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "allow_wishlist_push" field.</summary>
    public const int AllowWishlistPushFieldNumber = 3;
    private readonly static bool AllowWishlistPushDefaultValue = false;

    private bool allowWishlistPush_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AllowWishlistPush {
      get { if ((_hasBits0 & 2) != 0) { return allowWishlistPush_; } else { return AllowWishlistPushDefaultValue; } }
      set {
        _hasBits0 |= 2;
        allowWishlistPush_ = value;
      }
    }
    /// <summary>Gets whether the "allow_wishlist_push" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAllowWishlistPush {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "allow_wishlist_push" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAllowWishlistPush() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "has_settings" field.</summary>
    public const int HasSettingsFieldNumber = 4;
    private readonly static bool HasSettingsDefaultValue = false;

    private bool hasSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSettings {
      get { if ((_hasBits0 & 4) != 0) { return hasSettings_; } else { return HasSettingsDefaultValue; } }
      set {
        _hasBits0 |= 4;
        hasSettings_ = value;
      }
    }
    /// <summary>Gets whether the "has_settings" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHasSettings {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "has_settings" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHasSettings() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "chat_notification_level" field.</summary>
    public const int ChatNotificationLevelFieldNumber = 5;
    private readonly static uint ChatNotificationLevelDefaultValue = 0;

    private uint chatNotificationLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ChatNotificationLevel {
      get { if ((_hasBits0 & 8) != 0) { return chatNotificationLevel_; } else { return ChatNotificationLevelDefaultValue; } }
      set {
        _hasBits0 |= 8;
        chatNotificationLevel_ = value;
      }
    }
    /// <summary>Gets whether the "chat_notification_level" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasChatNotificationLevel {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "chat_notification_level" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearChatNotificationLevel() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "notify_direct_chat" field.</summary>
    public const int NotifyDirectChatFieldNumber = 6;
    private readonly static bool NotifyDirectChatDefaultValue = false;

    private bool notifyDirectChat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NotifyDirectChat {
      get { if ((_hasBits0 & 16) != 0) { return notifyDirectChat_; } else { return NotifyDirectChatDefaultValue; } }
      set {
        _hasBits0 |= 16;
        notifyDirectChat_ = value;
      }
    }
    /// <summary>Gets whether the "notify_direct_chat" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNotifyDirectChat {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "notify_direct_chat" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNotifyDirectChat() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "notify_group_chat" field.</summary>
    public const int NotifyGroupChatFieldNumber = 7;
    private readonly static bool NotifyGroupChatDefaultValue = false;

    private bool notifyGroupChat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NotifyGroupChat {
      get { if ((_hasBits0 & 32) != 0) { return notifyGroupChat_; } else { return NotifyGroupChatDefaultValue; } }
      set {
        _hasBits0 |= 32;
        notifyGroupChat_ = value;
      }
    }
    /// <summary>Gets whether the "notify_group_chat" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNotifyGroupChat {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "notify_group_chat" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNotifyGroupChat() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "allow_event_push" field.</summary>
    public const int AllowEventPushFieldNumber = 8;
    private readonly static bool AllowEventPushDefaultValue = true;

    private bool allowEventPush_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AllowEventPush {
      get { if ((_hasBits0 & 64) != 0) { return allowEventPush_; } else { return AllowEventPushDefaultValue; } }
      set {
        _hasBits0 |= 64;
        allowEventPush_ = value;
      }
    }
    /// <summary>Gets whether the "allow_event_push" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAllowEventPush {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "allow_event_push" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAllowEventPush() {
      _hasBits0 &= ~64;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CMobilePerAccount_GetSettings_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CMobilePerAccount_GetSettings_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AllowSalePush != other.AllowSalePush) return false;
      if (AllowWishlistPush != other.AllowWishlistPush) return false;
      if (HasSettings != other.HasSettings) return false;
      if (ChatNotificationLevel != other.ChatNotificationLevel) return false;
      if (NotifyDirectChat != other.NotifyDirectChat) return false;
      if (NotifyGroupChat != other.NotifyGroupChat) return false;
      if (AllowEventPush != other.AllowEventPush) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAllowSalePush) hash ^= AllowSalePush.GetHashCode();
      if (HasAllowWishlistPush) hash ^= AllowWishlistPush.GetHashCode();
      if (HasHasSettings) hash ^= HasSettings.GetHashCode();
      if (HasChatNotificationLevel) hash ^= ChatNotificationLevel.GetHashCode();
      if (HasNotifyDirectChat) hash ^= NotifyDirectChat.GetHashCode();
      if (HasNotifyGroupChat) hash ^= NotifyGroupChat.GetHashCode();
      if (HasAllowEventPush) hash ^= AllowEventPush.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAllowSalePush) {
        output.WriteRawTag(16);
        output.WriteBool(AllowSalePush);
      }
      if (HasAllowWishlistPush) {
        output.WriteRawTag(24);
        output.WriteBool(AllowWishlistPush);
      }
      if (HasHasSettings) {
        output.WriteRawTag(32);
        output.WriteBool(HasSettings);
      }
      if (HasChatNotificationLevel) {
        output.WriteRawTag(40);
        output.WriteUInt32(ChatNotificationLevel);
      }
      if (HasNotifyDirectChat) {
        output.WriteRawTag(48);
        output.WriteBool(NotifyDirectChat);
      }
      if (HasNotifyGroupChat) {
        output.WriteRawTag(56);
        output.WriteBool(NotifyGroupChat);
      }
      if (HasAllowEventPush) {
        output.WriteRawTag(64);
        output.WriteBool(AllowEventPush);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAllowSalePush) {
        output.WriteRawTag(16);
        output.WriteBool(AllowSalePush);
      }
      if (HasAllowWishlistPush) {
        output.WriteRawTag(24);
        output.WriteBool(AllowWishlistPush);
      }
      if (HasHasSettings) {
        output.WriteRawTag(32);
        output.WriteBool(HasSettings);
      }
      if (HasChatNotificationLevel) {
        output.WriteRawTag(40);
        output.WriteUInt32(ChatNotificationLevel);
      }
      if (HasNotifyDirectChat) {
        output.WriteRawTag(48);
        output.WriteBool(NotifyDirectChat);
      }
      if (HasNotifyGroupChat) {
        output.WriteRawTag(56);
        output.WriteBool(NotifyGroupChat);
      }
      if (HasAllowEventPush) {
        output.WriteRawTag(64);
        output.WriteBool(AllowEventPush);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAllowSalePush) {
        size += 1 + 1;
      }
      if (HasAllowWishlistPush) {
        size += 1 + 1;
      }
      if (HasHasSettings) {
        size += 1 + 1;
      }
      if (HasChatNotificationLevel) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChatNotificationLevel);
      }
      if (HasNotifyDirectChat) {
        size += 1 + 1;
      }
      if (HasNotifyGroupChat) {
        size += 1 + 1;
      }
      if (HasAllowEventPush) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CMobilePerAccount_GetSettings_Response other) {
      if (other == null) {
        return;
      }
      if (other.HasAllowSalePush) {
        AllowSalePush = other.AllowSalePush;
      }
      if (other.HasAllowWishlistPush) {
        AllowWishlistPush = other.AllowWishlistPush;
      }
      if (other.HasHasSettings) {
        HasSettings = other.HasSettings;
      }
      if (other.HasChatNotificationLevel) {
        ChatNotificationLevel = other.ChatNotificationLevel;
      }
      if (other.HasNotifyDirectChat) {
        NotifyDirectChat = other.NotifyDirectChat;
      }
      if (other.HasNotifyGroupChat) {
        NotifyGroupChat = other.NotifyGroupChat;
      }
      if (other.HasAllowEventPush) {
        AllowEventPush = other.AllowEventPush;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            AllowSalePush = input.ReadBool();
            break;
          }
          case 24: {
            AllowWishlistPush = input.ReadBool();
            break;
          }
          case 32: {
            HasSettings = input.ReadBool();
            break;
          }
          case 40: {
            ChatNotificationLevel = input.ReadUInt32();
            break;
          }
          case 48: {
            NotifyDirectChat = input.ReadBool();
            break;
          }
          case 56: {
            NotifyGroupChat = input.ReadBool();
            break;
          }
          case 64: {
            AllowEventPush = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            AllowSalePush = input.ReadBool();
            break;
          }
          case 24: {
            AllowWishlistPush = input.ReadBool();
            break;
          }
          case 32: {
            HasSettings = input.ReadBool();
            break;
          }
          case 40: {
            ChatNotificationLevel = input.ReadUInt32();
            break;
          }
          case 48: {
            NotifyDirectChat = input.ReadBool();
            break;
          }
          case 56: {
            NotifyGroupChat = input.ReadBool();
            break;
          }
          case 64: {
            AllowEventPush = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CMobilePerAccount_SetSettings_Request : pb::IMessage<CMobilePerAccount_SetSettings_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CMobilePerAccount_SetSettings_Request> _parser = new pb::MessageParser<CMobilePerAccount_SetSettings_Request>(() => new CMobilePerAccount_SetSettings_Request());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CMobilePerAccount_SetSettings_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServiceMobileperaccountReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_SetSettings_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_SetSettings_Request(CMobilePerAccount_SetSettings_Request other) : this() {
      _hasBits0 = other._hasBits0;
      allowSalePush_ = other.allowSalePush_;
      allowWishlistPush_ = other.allowWishlistPush_;
      chatNotificationLevel_ = other.chatNotificationLevel_;
      notifyDirectChat_ = other.notifyDirectChat_;
      notifyGroupChat_ = other.notifyGroupChat_;
      allowEventPush_ = other.allowEventPush_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_SetSettings_Request Clone() {
      return new CMobilePerAccount_SetSettings_Request(this);
    }

    /// <summary>Field number for the "allow_sale_push" field.</summary>
    public const int AllowSalePushFieldNumber = 2;
    private readonly static bool AllowSalePushDefaultValue = false;

    private bool allowSalePush_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AllowSalePush {
      get { if ((_hasBits0 & 1) != 0) { return allowSalePush_; } else { return AllowSalePushDefaultValue; } }
      set {
        _hasBits0 |= 1;
        allowSalePush_ = value;
      }
    }
    /// <summary>Gets whether the "allow_sale_push" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAllowSalePush {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "allow_sale_push" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAllowSalePush() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "allow_wishlist_push" field.</summary>
    public const int AllowWishlistPushFieldNumber = 3;
    private readonly static bool AllowWishlistPushDefaultValue = false;

    private bool allowWishlistPush_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AllowWishlistPush {
      get { if ((_hasBits0 & 2) != 0) { return allowWishlistPush_; } else { return AllowWishlistPushDefaultValue; } }
      set {
        _hasBits0 |= 2;
        allowWishlistPush_ = value;
      }
    }
    /// <summary>Gets whether the "allow_wishlist_push" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAllowWishlistPush {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "allow_wishlist_push" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAllowWishlistPush() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "chat_notification_level" field.</summary>
    public const int ChatNotificationLevelFieldNumber = 4;
    private readonly static uint ChatNotificationLevelDefaultValue = 0;

    private uint chatNotificationLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ChatNotificationLevel {
      get { if ((_hasBits0 & 4) != 0) { return chatNotificationLevel_; } else { return ChatNotificationLevelDefaultValue; } }
      set {
        _hasBits0 |= 4;
        chatNotificationLevel_ = value;
      }
    }
    /// <summary>Gets whether the "chat_notification_level" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasChatNotificationLevel {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "chat_notification_level" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearChatNotificationLevel() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "notify_direct_chat" field.</summary>
    public const int NotifyDirectChatFieldNumber = 5;
    private readonly static bool NotifyDirectChatDefaultValue = false;

    private bool notifyDirectChat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NotifyDirectChat {
      get { if ((_hasBits0 & 8) != 0) { return notifyDirectChat_; } else { return NotifyDirectChatDefaultValue; } }
      set {
        _hasBits0 |= 8;
        notifyDirectChat_ = value;
      }
    }
    /// <summary>Gets whether the "notify_direct_chat" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNotifyDirectChat {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "notify_direct_chat" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNotifyDirectChat() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "notify_group_chat" field.</summary>
    public const int NotifyGroupChatFieldNumber = 6;
    private readonly static bool NotifyGroupChatDefaultValue = false;

    private bool notifyGroupChat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NotifyGroupChat {
      get { if ((_hasBits0 & 16) != 0) { return notifyGroupChat_; } else { return NotifyGroupChatDefaultValue; } }
      set {
        _hasBits0 |= 16;
        notifyGroupChat_ = value;
      }
    }
    /// <summary>Gets whether the "notify_group_chat" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNotifyGroupChat {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "notify_group_chat" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNotifyGroupChat() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "allow_event_push" field.</summary>
    public const int AllowEventPushFieldNumber = 7;
    private readonly static bool AllowEventPushDefaultValue = true;

    private bool allowEventPush_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AllowEventPush {
      get { if ((_hasBits0 & 32) != 0) { return allowEventPush_; } else { return AllowEventPushDefaultValue; } }
      set {
        _hasBits0 |= 32;
        allowEventPush_ = value;
      }
    }
    /// <summary>Gets whether the "allow_event_push" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAllowEventPush {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "allow_event_push" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAllowEventPush() {
      _hasBits0 &= ~32;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CMobilePerAccount_SetSettings_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CMobilePerAccount_SetSettings_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AllowSalePush != other.AllowSalePush) return false;
      if (AllowWishlistPush != other.AllowWishlistPush) return false;
      if (ChatNotificationLevel != other.ChatNotificationLevel) return false;
      if (NotifyDirectChat != other.NotifyDirectChat) return false;
      if (NotifyGroupChat != other.NotifyGroupChat) return false;
      if (AllowEventPush != other.AllowEventPush) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAllowSalePush) hash ^= AllowSalePush.GetHashCode();
      if (HasAllowWishlistPush) hash ^= AllowWishlistPush.GetHashCode();
      if (HasChatNotificationLevel) hash ^= ChatNotificationLevel.GetHashCode();
      if (HasNotifyDirectChat) hash ^= NotifyDirectChat.GetHashCode();
      if (HasNotifyGroupChat) hash ^= NotifyGroupChat.GetHashCode();
      if (HasAllowEventPush) hash ^= AllowEventPush.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAllowSalePush) {
        output.WriteRawTag(16);
        output.WriteBool(AllowSalePush);
      }
      if (HasAllowWishlistPush) {
        output.WriteRawTag(24);
        output.WriteBool(AllowWishlistPush);
      }
      if (HasChatNotificationLevel) {
        output.WriteRawTag(32);
        output.WriteUInt32(ChatNotificationLevel);
      }
      if (HasNotifyDirectChat) {
        output.WriteRawTag(40);
        output.WriteBool(NotifyDirectChat);
      }
      if (HasNotifyGroupChat) {
        output.WriteRawTag(48);
        output.WriteBool(NotifyGroupChat);
      }
      if (HasAllowEventPush) {
        output.WriteRawTag(56);
        output.WriteBool(AllowEventPush);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAllowSalePush) {
        output.WriteRawTag(16);
        output.WriteBool(AllowSalePush);
      }
      if (HasAllowWishlistPush) {
        output.WriteRawTag(24);
        output.WriteBool(AllowWishlistPush);
      }
      if (HasChatNotificationLevel) {
        output.WriteRawTag(32);
        output.WriteUInt32(ChatNotificationLevel);
      }
      if (HasNotifyDirectChat) {
        output.WriteRawTag(40);
        output.WriteBool(NotifyDirectChat);
      }
      if (HasNotifyGroupChat) {
        output.WriteRawTag(48);
        output.WriteBool(NotifyGroupChat);
      }
      if (HasAllowEventPush) {
        output.WriteRawTag(56);
        output.WriteBool(AllowEventPush);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAllowSalePush) {
        size += 1 + 1;
      }
      if (HasAllowWishlistPush) {
        size += 1 + 1;
      }
      if (HasChatNotificationLevel) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChatNotificationLevel);
      }
      if (HasNotifyDirectChat) {
        size += 1 + 1;
      }
      if (HasNotifyGroupChat) {
        size += 1 + 1;
      }
      if (HasAllowEventPush) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CMobilePerAccount_SetSettings_Request other) {
      if (other == null) {
        return;
      }
      if (other.HasAllowSalePush) {
        AllowSalePush = other.AllowSalePush;
      }
      if (other.HasAllowWishlistPush) {
        AllowWishlistPush = other.AllowWishlistPush;
      }
      if (other.HasChatNotificationLevel) {
        ChatNotificationLevel = other.ChatNotificationLevel;
      }
      if (other.HasNotifyDirectChat) {
        NotifyDirectChat = other.NotifyDirectChat;
      }
      if (other.HasNotifyGroupChat) {
        NotifyGroupChat = other.NotifyGroupChat;
      }
      if (other.HasAllowEventPush) {
        AllowEventPush = other.AllowEventPush;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            AllowSalePush = input.ReadBool();
            break;
          }
          case 24: {
            AllowWishlistPush = input.ReadBool();
            break;
          }
          case 32: {
            ChatNotificationLevel = input.ReadUInt32();
            break;
          }
          case 40: {
            NotifyDirectChat = input.ReadBool();
            break;
          }
          case 48: {
            NotifyGroupChat = input.ReadBool();
            break;
          }
          case 56: {
            AllowEventPush = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            AllowSalePush = input.ReadBool();
            break;
          }
          case 24: {
            AllowWishlistPush = input.ReadBool();
            break;
          }
          case 32: {
            ChatNotificationLevel = input.ReadUInt32();
            break;
          }
          case 40: {
            NotifyDirectChat = input.ReadBool();
            break;
          }
          case 48: {
            NotifyGroupChat = input.ReadBool();
            break;
          }
          case 56: {
            AllowEventPush = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CMobilePerAccount_SetSettings_Response : pb::IMessage<CMobilePerAccount_SetSettings_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CMobilePerAccount_SetSettings_Response> _parser = new pb::MessageParser<CMobilePerAccount_SetSettings_Response>(() => new CMobilePerAccount_SetSettings_Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CMobilePerAccount_SetSettings_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenSteamworks.Protobuf.WebUI.ServiceMobileperaccountReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_SetSettings_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_SetSettings_Response(CMobilePerAccount_SetSettings_Response other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CMobilePerAccount_SetSettings_Response Clone() {
      return new CMobilePerAccount_SetSettings_Response(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CMobilePerAccount_SetSettings_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CMobilePerAccount_SetSettings_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CMobilePerAccount_SetSettings_Response other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
