// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: steammessages_remoteclient_service.steamclient.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenSteamworks.Protobuf {

  /// <summary>Holder for reflection information generated from steammessages_remoteclient_service.steamclient.proto</summary>
  public static partial class SteammessagesRemoteclientServiceSteamclientReflection {

    #region Descriptor
    /// <summary>File descriptor for steammessages_remoteclient_service.steamclient.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SteammessagesRemoteclientServiceSteamclientReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRzdGVhbW1lc3NhZ2VzX3JlbW90ZWNsaWVudF9zZXJ2aWNlLnN0ZWFtY2xp",
            "ZW50LnByb3RvGiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRvci5wcm90bxoY",
            "c3RlYW1tZXNzYWdlc19iYXNlLnByb3RvGixzdGVhbW1lc3NhZ2VzX3VuaWZp",
            "ZWRfYmFzZS5zdGVhbWNsaWVudC5wcm90bxoxc3RlYW1tZXNzYWdlc19yZW1v",
            "dGVjbGllbnRfc2VydmljZV9tZXNzYWdlcy5wcm90bzLKDgoMUmVtb3RlQ2xp",
            "ZW50EogBCg5HZXRQYWlyaW5nSW5mbxIlLkNSZW1vdGVDbGllbnRfR2V0UGFp",
            "cmluZ0luZm9fUmVxdWVzdBomLkNSZW1vdGVDbGllbnRfR2V0UGFpcmluZ0lu",
            "Zm9fUmVzcG9uc2UiJ4K1GCNHZXQgcGFpcmluZyBpbmZvIGZvciBhbiBlbnRl",
            "cmVkIFBJThJ+CgxOb3RpZnlPbmxpbmUSIi5DUmVtb3RlQ2xpZW50X09ubGlu",
            "ZV9Ob3RpZmljYXRpb24aCy5Ob1Jlc3BvbnNlIj2CtRg5TGV0IHRoZSBzZXJ2",
            "aWNlIGtub3cgd2UncmUgYXZhaWxhYmxlIGZvciBzdGF0dXMgbGlzdGVuZXJz",
            "Em4KEU5vdGlmeVJlcGx5UGFja2V0EicuQ1JlbW90ZUNsaWVudF9SZXBseVBh",
            "Y2tldF9Ob3RpZmljYXRpb24aCy5Ob1Jlc3BvbnNlIiOCtRgfU2VuZCBhIHJl",
            "cGx5IHRvIGEgcmVtb3RlIGNsaWVudBKnAQoTQWxsb2NhdGVSZWxheVNlcnZl",
            "chIqLkNSZW1vdGVDbGllbnRfQWxsb2NhdGVSZWxheVNlcnZlcl9SZXF1ZXN0",
            "GisuQ1JlbW90ZUNsaWVudF9BbGxvY2F0ZVJlbGF5U2VydmVyX1Jlc3BvbnNl",
            "IjeCtRgzQWxsb2NhdGUgYSBVRFAgcmVsYXkgc2VydmVyIGZvciBhIHN0cmVh",
            "bWluZyBzZXNzaW9uEn0KC0FsbG9jYXRlU0RSEiIuQ1JlbW90ZUNsaWVudF9B",
            "bGxvY2F0ZVNEUl9SZXF1ZXN0GiMuQ1JlbW90ZUNsaWVudF9BbGxvY2F0ZVNE",
            "Ul9SZXNwb25zZSIlgrUYIUFsbG9jYXRlIFNEUiByZXNvdXJjZXMgZm9yIGFu",
            "IGFwcBKDAQoYU2VuZFN0ZWFtQnJvYWRjYXN0UGFja2V0EiouQ1JlbW90ZUNs",
            "aWVudF9TdGVhbUJyb2FkY2FzdF9Ob3RpZmljYXRpb24aCy5Ob1Jlc3BvbnNl",
            "Ii6CtRgqQnJvYWRjYXN0IGEgcGFja2V0IHRvIHJlbW90ZSBTdGVhbSBjbGll",
            "bnRzEnsKFlNlbmRTdGVhbVRvU3RlYW1QYWNrZXQSKC5DUmVtb3RlQ2xpZW50",
            "X1N0ZWFtVG9TdGVhbV9Ob3RpZmljYXRpb24aCy5Ob1Jlc3BvbnNlIiqCtRgm",
            "U2VuZCBhIHBhY2tldCB0byBhIHJlbW90ZSBTdGVhbSBjbGllbnQSqAEKHFNl",
            "bmRSZW1vdGVQbGF5U2Vzc2lvblN0YXJ0ZWQSIy5DUmVtb3RlUGxheV9TZXNz",
            "aW9uU3RhcnRlZF9SZXF1ZXN0GiQuQ1JlbW90ZVBsYXlfU2Vzc2lvblN0YXJ0",
            "ZWRfUmVzcG9uc2UiPYK1GDlMZXQgdGhlIHNlcnZlciBrbm93IHRoYXQgd2Ug",
            "c3RhcnRlZCBhIFJlbW90ZSBQbGF5IHNlc3Npb24SlAEKHFNlbmRSZW1vdGVQ",
            "bGF5U2Vzc2lvblN0b3BwZWQSKC5DUmVtb3RlUGxheV9TZXNzaW9uU3RvcHBl",
            "ZF9Ob3RpZmljYXRpb24aCy5Ob1Jlc3BvbnNlIj2CtRg5TGV0IHRoZSBzZXJ2",
            "ZXIga25vdyB0aGF0IHdlIHN0b3BwZWQgYSBSZW1vdGUgUGxheSBzZXNzaW9u",
            "EogBChxTZW5kUmVtb3RlUGxheVRvZ2V0aGVyUGFja2V0EiEuQ1JlbW90ZVBs",
            "YXlUb2dldGhlcl9Ob3RpZmljYXRpb24aCy5Ob1Jlc3BvbnNlIjiCtRg0U2Vu",
            "ZCBhIFJlbW90ZSBQbGF5IFRvZ2V0aGVyIHBhY2tldCB0byBhIFN0ZWFtIGNs",
            "aWVudBLJAQoiQ3JlYXRlUmVtb3RlUGxheVRvZ2V0aGVySW52aXRhdGlvbhI5",
            "LkNSZW1vdGVDbGllbnRfQ3JlYXRlUmVtb3RlUGxheVRvZ2V0aGVySW52aXRh",
            "dGlvbl9SZXF1ZXN0GjouQ1JlbW90ZUNsaWVudF9DcmVhdGVSZW1vdGVQbGF5",
            "VG9nZXRoZXJJbnZpdGF0aW9uX1Jlc3BvbnNlIiyCtRgoQ3JlYXRlIGEgUmVt",
            "b3RlIFBsYXkgVG9nZXRoZXIgaW52aXRhdGlvbhLJAQoiRGVsZXRlUmVtb3Rl",
            "UGxheVRvZ2V0aGVySW52aXRhdGlvbhI5LkNSZW1vdGVDbGllbnRfRGVsZXRl",
            "UmVtb3RlUGxheVRvZ2V0aGVySW52aXRhdGlvbl9SZXF1ZXN0GjouQ1JlbW90",
            "ZUNsaWVudF9EZWxldGVSZW1vdGVQbGF5VG9nZXRoZXJJbnZpdGF0aW9uX1Jl",
            "c3BvbnNlIiyCtRgoRGVsZXRlIGEgUmVtb3RlIFBsYXkgVG9nZXRoZXIgaW52",
            "aXRhdGlvbhougrUYKk1ldGhvZHMgZm9yIFN0ZWFtIHJlbW90ZSBjbGllbnQg",
            "b3BlcmF0aW9uczKUBwoXUmVtb3RlQ2xpZW50U3RlYW1DbGllbnQSkAEKGk5v",
            "dGlmeVJlZ2lzdGVyU3RhdHVzVXBkYXRlEjAuQ1JlbW90ZUNsaWVudF9SZWdp",
            "c3RlclN0YXR1c1VwZGF0ZV9Ob3RpZmljYXRpb24aCy5Ob1Jlc3BvbnNlIjOC",
            "tRgvUmVnaXN0ZXIgZm9yIHN0YXR1cyB1cGRhdGVzIHdpdGggYSBTdGVhbSBj",
            "bGllbnQSlgEKHE5vdGlmeVVucmVnaXN0ZXJTdGF0dXNVcGRhdGUSMi5DUmVt",
            "b3RlQ2xpZW50X1VucmVnaXN0ZXJTdGF0dXNVcGRhdGVfTm90aWZpY2F0aW9u",
            "GgsuTm9SZXNwb25zZSI1grUYMVVucmVnaXN0ZXIgZm9yIHN0YXR1cyB1cGRh",
            "dGVzIHdpdGggYSBTdGVhbSBjbGllbnQScAoSTm90aWZ5UmVtb3RlUGFja2V0",
            "EiguQ1JlbW90ZUNsaWVudF9SZW1vdGVQYWNrZXRfTm90aWZpY2F0aW9uGgsu",
            "Tm9SZXNwb25zZSIjgrUYH1NlbmQgYSBwYWNrZXQgdG8gYSBTdGVhbSBjbGll",
            "bnQShQEKGk5vdGlmeVN0ZWFtQnJvYWRjYXN0UGFja2V0EiouQ1JlbW90ZUNs",
            "aWVudF9TdGVhbUJyb2FkY2FzdF9Ob3RpZmljYXRpb24aCy5Ob1Jlc3BvbnNl",
            "Ii6CtRgqQnJvYWRjYXN0IGEgcGFja2V0IHRvIHJlbW90ZSBTdGVhbSBjbGll",
            "bnRzEpEBChhOb3RpZnlTdGVhbVRvU3RlYW1QYWNrZXQSKC5DUmVtb3RlQ2xp",
            "ZW50X1N0ZWFtVG9TdGVhbV9Ob3RpZmljYXRpb24aCy5Ob1Jlc3BvbnNlIj6C",
            "tRg6U2VuZCBhIHBhY2tldCB0byBhIFN0ZWFtIGNsaWVudCBmcm9tIGEgcmVt",
            "b3RlIFN0ZWFtIGNsaWVudBKKAQoeTm90aWZ5UmVtb3RlUGxheVRvZ2V0aGVy",
            "UGFja2V0EiEuQ1JlbW90ZVBsYXlUb2dldGhlcl9Ob3RpZmljYXRpb24aCy5O",
            "b1Jlc3BvbnNlIjiCtRg0U2VuZCBhIFJlbW90ZSBQbGF5IFRvZ2V0aGVyIHBh",
            "Y2tldCB0byBhIFN0ZWFtIGNsaWVudBoygrUYKk1ldGhvZHMgZm9yIFN0ZWFt",
            "IHJlbW90ZSBjbGllbnQgb3BlcmF0aW9uc8C1GAJCHYABAaoCF09wZW5TdGVh",
            "bXdvcmtzLlByb3RvYnVm"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, global::OpenSteamworks.Protobuf.SteammessagesBaseReflection.Descriptor, global::OpenSteamworks.Protobuf.SteammessagesUnifiedBaseSteamclientReflection.Descriptor, global::OpenSteamworks.Protobuf.SteammessagesRemoteclientServiceMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
