// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: steammessages_clientlanp2p.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from steammessages_clientlanp2p.proto</summary>
public static partial class SteammessagesClientlanp2PReflection {

  #region Descriptor
  /// <summary>File descriptor for steammessages_clientlanp2p.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SteammessagesClientlanp2PReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiBzdGVhbW1lc3NhZ2VzX2NsaWVudGxhbnAycC5wcm90bxoYc3RlYW1tZXNz",
          "YWdlc19iYXNlLnByb3RvIocBCh1DTXNnQ2xpZW50TEFOUDJQUmVxdWVzdENo",
          "dW5rcxI7CgpjaHVua19rZXlzGAEgAygLMicuQ01zZ0NsaWVudExBTlAyUFJl",
          "cXVlc3RDaHVua3MuQ2h1bmtLZXkaKQoIQ2h1bmtLZXkSEAoIZGVwb3RfaWQY",
          "ASABKA0SCwoDc2hhGAIgASgMIukBCiVDTXNnQ2xpZW50TEFOUDJQUmVxdWVz",
          "dENodW5rc1Jlc3BvbnNlEkkKD2NodW5rX3Jlc3BvbnNlcxgBIAMoCzIwLkNN",
          "c2dDbGllbnRMQU5QMlBSZXF1ZXN0Q2h1bmtzUmVzcG9uc2UuQ2h1bmtEYXRh",
          "GnUKCUNodW5rRGF0YRIOCgZyZXN1bHQYASABKA0SEAoIZGVwb3RfaWQYAiAB",
          "KA0SCwoDc2hhGAMgASgMEhIKCmNodW5rX2RhdGEYBCABKAwSEQoJZW5jcnlw",
          "dGVkGAUgASgIEhIKCmNvbXByZXNzZWQYBiABKAgiSwoaQ01zZ0NsaWVudFBl",
          "ZXJDaHVua1JlcXVlc3QSDgoGYXBwX2lkGAEgASgNEhAKCGRlcG90X2lkGAIg",
          "ASgNEgsKA3NoYRgDIAEoDCKXAQobQ01zZ0NsaWVudFBlZXJDaHVua1Jlc3Bv",
          "bnNlEg4KBnJlc3VsdBgBIAEoDRIOCgZhcHBfaWQYAiABKA0SEAoIZGVwb3Rf",
          "aWQYAyABKA0SCwoDc2hhGAQgASgMEhEKCWVuY3J5cHRlZBgFIAEoCBISCgpj",
          "b21wcmVzc2VkGAYgASgIEhIKCmNodW5rX2RhdGEYByABKAxCBUgBgAEA"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::SteammessagesBaseReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::CMsgClientLANP2PRequestChunks), global::CMsgClientLANP2PRequestChunks.Parser, new[]{ "ChunkKeys" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::CMsgClientLANP2PRequestChunks.Types.ChunkKey), global::CMsgClientLANP2PRequestChunks.Types.ChunkKey.Parser, new[]{ "DepotId", "Sha" }, null, null, null, null)}),
          new pbr::GeneratedClrTypeInfo(typeof(global::CMsgClientLANP2PRequestChunksResponse), global::CMsgClientLANP2PRequestChunksResponse.Parser, new[]{ "ChunkResponses" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::CMsgClientLANP2PRequestChunksResponse.Types.ChunkData), global::CMsgClientLANP2PRequestChunksResponse.Types.ChunkData.Parser, new[]{ "Result", "DepotId", "Sha", "ChunkData_", "Encrypted", "Compressed" }, null, null, null, null)}),
          new pbr::GeneratedClrTypeInfo(typeof(global::CMsgClientPeerChunkRequest), global::CMsgClientPeerChunkRequest.Parser, new[]{ "AppId", "DepotId", "Sha" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CMsgClientPeerChunkResponse), global::CMsgClientPeerChunkResponse.Parser, new[]{ "Result", "AppId", "DepotId", "Sha", "Encrypted", "Compressed", "ChunkData" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class CMsgClientLANP2PRequestChunks : pb::IMessage<CMsgClientLANP2PRequestChunks>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CMsgClientLANP2PRequestChunks> _parser = new pb::MessageParser<CMsgClientLANP2PRequestChunks>(() => new CMsgClientLANP2PRequestChunks());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CMsgClientLANP2PRequestChunks> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SteammessagesClientlanp2PReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientLANP2PRequestChunks() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientLANP2PRequestChunks(CMsgClientLANP2PRequestChunks other) : this() {
    chunkKeys_ = other.chunkKeys_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientLANP2PRequestChunks Clone() {
    return new CMsgClientLANP2PRequestChunks(this);
  }

  /// <summary>Field number for the "chunk_keys" field.</summary>
  public const int ChunkKeysFieldNumber = 1;
  private static readonly pb::FieldCodec<global::CMsgClientLANP2PRequestChunks.Types.ChunkKey> _repeated_chunkKeys_codec
      = pb::FieldCodec.ForMessage(10, global::CMsgClientLANP2PRequestChunks.Types.ChunkKey.Parser);
  private readonly pbc::RepeatedField<global::CMsgClientLANP2PRequestChunks.Types.ChunkKey> chunkKeys_ = new pbc::RepeatedField<global::CMsgClientLANP2PRequestChunks.Types.ChunkKey>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::CMsgClientLANP2PRequestChunks.Types.ChunkKey> ChunkKeys {
    get { return chunkKeys_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CMsgClientLANP2PRequestChunks);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CMsgClientLANP2PRequestChunks other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!chunkKeys_.Equals(other.chunkKeys_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= chunkKeys_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    chunkKeys_.WriteTo(output, _repeated_chunkKeys_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    chunkKeys_.WriteTo(ref output, _repeated_chunkKeys_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += chunkKeys_.CalculateSize(_repeated_chunkKeys_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CMsgClientLANP2PRequestChunks other) {
    if (other == null) {
      return;
    }
    chunkKeys_.Add(other.chunkKeys_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          chunkKeys_.AddEntriesFrom(input, _repeated_chunkKeys_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          chunkKeys_.AddEntriesFrom(ref input, _repeated_chunkKeys_codec);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the CMsgClientLANP2PRequestChunks message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public sealed partial class ChunkKey : pb::IMessage<ChunkKey>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<ChunkKey> _parser = new pb::MessageParser<ChunkKey>(() => new ChunkKey());
      private pb::UnknownFieldSet _unknownFields;
      private int _hasBits0;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<ChunkKey> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::CMsgClientLANP2PRequestChunks.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public ChunkKey() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public ChunkKey(ChunkKey other) : this() {
        _hasBits0 = other._hasBits0;
        depotId_ = other.depotId_;
        sha_ = other.sha_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public ChunkKey Clone() {
        return new ChunkKey(this);
      }

      /// <summary>Field number for the "depot_id" field.</summary>
      public const int DepotIdFieldNumber = 1;
      private readonly static uint DepotIdDefaultValue = 0;

      private uint depotId_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint DepotId {
        get { if ((_hasBits0 & 1) != 0) { return depotId_; } else { return DepotIdDefaultValue; } }
        set {
          _hasBits0 |= 1;
          depotId_ = value;
        }
      }
      /// <summary>Gets whether the "depot_id" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasDepotId {
        get { return (_hasBits0 & 1) != 0; }
      }
      /// <summary>Clears the value of the "depot_id" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearDepotId() {
        _hasBits0 &= ~1;
      }

      /// <summary>Field number for the "sha" field.</summary>
      public const int ShaFieldNumber = 2;
      private readonly static pb::ByteString ShaDefaultValue = pb::ByteString.Empty;

      private pb::ByteString sha_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pb::ByteString Sha {
        get { return sha_ ?? ShaDefaultValue; }
        set {
          sha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }
      /// <summary>Gets whether the "sha" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasSha {
        get { return sha_ != null; }
      }
      /// <summary>Clears the value of the "sha" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearSha() {
        sha_ = null;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as ChunkKey);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(ChunkKey other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (DepotId != other.DepotId) return false;
        if (Sha != other.Sha) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (HasDepotId) hash ^= DepotId.GetHashCode();
        if (HasSha) hash ^= Sha.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (HasDepotId) {
          output.WriteRawTag(8);
          output.WriteUInt32(DepotId);
        }
        if (HasSha) {
          output.WriteRawTag(18);
          output.WriteBytes(Sha);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (HasDepotId) {
          output.WriteRawTag(8);
          output.WriteUInt32(DepotId);
        }
        if (HasSha) {
          output.WriteRawTag(18);
          output.WriteBytes(Sha);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (HasDepotId) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DepotId);
        }
        if (HasSha) {
          size += 1 + pb::CodedOutputStream.ComputeBytesSize(Sha);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(ChunkKey other) {
        if (other == null) {
          return;
        }
        if (other.HasDepotId) {
          DepotId = other.DepotId;
        }
        if (other.HasSha) {
          Sha = other.Sha;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 8: {
              DepotId = input.ReadUInt32();
              break;
            }
            case 18: {
              Sha = input.ReadBytes();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 8: {
              DepotId = input.ReadUInt32();
              break;
            }
            case 18: {
              Sha = input.ReadBytes();
              break;
            }
          }
        }
      }
      #endif

    }

  }
  #endregion

}

public sealed partial class CMsgClientLANP2PRequestChunksResponse : pb::IMessage<CMsgClientLANP2PRequestChunksResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CMsgClientLANP2PRequestChunksResponse> _parser = new pb::MessageParser<CMsgClientLANP2PRequestChunksResponse>(() => new CMsgClientLANP2PRequestChunksResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CMsgClientLANP2PRequestChunksResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SteammessagesClientlanp2PReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientLANP2PRequestChunksResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientLANP2PRequestChunksResponse(CMsgClientLANP2PRequestChunksResponse other) : this() {
    chunkResponses_ = other.chunkResponses_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientLANP2PRequestChunksResponse Clone() {
    return new CMsgClientLANP2PRequestChunksResponse(this);
  }

  /// <summary>Field number for the "chunk_responses" field.</summary>
  public const int ChunkResponsesFieldNumber = 1;
  private static readonly pb::FieldCodec<global::CMsgClientLANP2PRequestChunksResponse.Types.ChunkData> _repeated_chunkResponses_codec
      = pb::FieldCodec.ForMessage(10, global::CMsgClientLANP2PRequestChunksResponse.Types.ChunkData.Parser);
  private readonly pbc::RepeatedField<global::CMsgClientLANP2PRequestChunksResponse.Types.ChunkData> chunkResponses_ = new pbc::RepeatedField<global::CMsgClientLANP2PRequestChunksResponse.Types.ChunkData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::CMsgClientLANP2PRequestChunksResponse.Types.ChunkData> ChunkResponses {
    get { return chunkResponses_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CMsgClientLANP2PRequestChunksResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CMsgClientLANP2PRequestChunksResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!chunkResponses_.Equals(other.chunkResponses_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= chunkResponses_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    chunkResponses_.WriteTo(output, _repeated_chunkResponses_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    chunkResponses_.WriteTo(ref output, _repeated_chunkResponses_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += chunkResponses_.CalculateSize(_repeated_chunkResponses_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CMsgClientLANP2PRequestChunksResponse other) {
    if (other == null) {
      return;
    }
    chunkResponses_.Add(other.chunkResponses_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          chunkResponses_.AddEntriesFrom(input, _repeated_chunkResponses_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          chunkResponses_.AddEntriesFrom(ref input, _repeated_chunkResponses_codec);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the CMsgClientLANP2PRequestChunksResponse message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public sealed partial class ChunkData : pb::IMessage<ChunkData>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<ChunkData> _parser = new pb::MessageParser<ChunkData>(() => new ChunkData());
      private pb::UnknownFieldSet _unknownFields;
      private int _hasBits0;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<ChunkData> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::CMsgClientLANP2PRequestChunksResponse.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public ChunkData() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public ChunkData(ChunkData other) : this() {
        _hasBits0 = other._hasBits0;
        result_ = other.result_;
        depotId_ = other.depotId_;
        sha_ = other.sha_;
        chunkData_ = other.chunkData_;
        encrypted_ = other.encrypted_;
        compressed_ = other.compressed_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public ChunkData Clone() {
        return new ChunkData(this);
      }

      /// <summary>Field number for the "result" field.</summary>
      public const int ResultFieldNumber = 1;
      private readonly static uint ResultDefaultValue = 0;

      private uint result_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint Result {
        get { if ((_hasBits0 & 1) != 0) { return result_; } else { return ResultDefaultValue; } }
        set {
          _hasBits0 |= 1;
          result_ = value;
        }
      }
      /// <summary>Gets whether the "result" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasResult {
        get { return (_hasBits0 & 1) != 0; }
      }
      /// <summary>Clears the value of the "result" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearResult() {
        _hasBits0 &= ~1;
      }

      /// <summary>Field number for the "depot_id" field.</summary>
      public const int DepotIdFieldNumber = 2;
      private readonly static uint DepotIdDefaultValue = 0;

      private uint depotId_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint DepotId {
        get { if ((_hasBits0 & 2) != 0) { return depotId_; } else { return DepotIdDefaultValue; } }
        set {
          _hasBits0 |= 2;
          depotId_ = value;
        }
      }
      /// <summary>Gets whether the "depot_id" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasDepotId {
        get { return (_hasBits0 & 2) != 0; }
      }
      /// <summary>Clears the value of the "depot_id" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearDepotId() {
        _hasBits0 &= ~2;
      }

      /// <summary>Field number for the "sha" field.</summary>
      public const int ShaFieldNumber = 3;
      private readonly static pb::ByteString ShaDefaultValue = pb::ByteString.Empty;

      private pb::ByteString sha_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pb::ByteString Sha {
        get { return sha_ ?? ShaDefaultValue; }
        set {
          sha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }
      /// <summary>Gets whether the "sha" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasSha {
        get { return sha_ != null; }
      }
      /// <summary>Clears the value of the "sha" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearSha() {
        sha_ = null;
      }

      /// <summary>Field number for the "chunk_data" field.</summary>
      public const int ChunkData_FieldNumber = 4;
      private readonly static pb::ByteString ChunkData_DefaultValue = pb::ByteString.Empty;

      private pb::ByteString chunkData_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pb::ByteString ChunkData_ {
        get { return chunkData_ ?? ChunkData_DefaultValue; }
        set {
          chunkData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }
      /// <summary>Gets whether the "chunk_data" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasChunkData_ {
        get { return chunkData_ != null; }
      }
      /// <summary>Clears the value of the "chunk_data" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearChunkData_() {
        chunkData_ = null;
      }

      /// <summary>Field number for the "encrypted" field.</summary>
      public const int EncryptedFieldNumber = 5;
      private readonly static bool EncryptedDefaultValue = false;

      private bool encrypted_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Encrypted {
        get { if ((_hasBits0 & 4) != 0) { return encrypted_; } else { return EncryptedDefaultValue; } }
        set {
          _hasBits0 |= 4;
          encrypted_ = value;
        }
      }
      /// <summary>Gets whether the "encrypted" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasEncrypted {
        get { return (_hasBits0 & 4) != 0; }
      }
      /// <summary>Clears the value of the "encrypted" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearEncrypted() {
        _hasBits0 &= ~4;
      }

      /// <summary>Field number for the "compressed" field.</summary>
      public const int CompressedFieldNumber = 6;
      private readonly static bool CompressedDefaultValue = false;

      private bool compressed_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Compressed {
        get { if ((_hasBits0 & 8) != 0) { return compressed_; } else { return CompressedDefaultValue; } }
        set {
          _hasBits0 |= 8;
          compressed_ = value;
        }
      }
      /// <summary>Gets whether the "compressed" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasCompressed {
        get { return (_hasBits0 & 8) != 0; }
      }
      /// <summary>Clears the value of the "compressed" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearCompressed() {
        _hasBits0 &= ~8;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as ChunkData);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(ChunkData other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (Result != other.Result) return false;
        if (DepotId != other.DepotId) return false;
        if (Sha != other.Sha) return false;
        if (ChunkData_ != other.ChunkData_) return false;
        if (Encrypted != other.Encrypted) return false;
        if (Compressed != other.Compressed) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (HasResult) hash ^= Result.GetHashCode();
        if (HasDepotId) hash ^= DepotId.GetHashCode();
        if (HasSha) hash ^= Sha.GetHashCode();
        if (HasChunkData_) hash ^= ChunkData_.GetHashCode();
        if (HasEncrypted) hash ^= Encrypted.GetHashCode();
        if (HasCompressed) hash ^= Compressed.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (HasResult) {
          output.WriteRawTag(8);
          output.WriteUInt32(Result);
        }
        if (HasDepotId) {
          output.WriteRawTag(16);
          output.WriteUInt32(DepotId);
        }
        if (HasSha) {
          output.WriteRawTag(26);
          output.WriteBytes(Sha);
        }
        if (HasChunkData_) {
          output.WriteRawTag(34);
          output.WriteBytes(ChunkData_);
        }
        if (HasEncrypted) {
          output.WriteRawTag(40);
          output.WriteBool(Encrypted);
        }
        if (HasCompressed) {
          output.WriteRawTag(48);
          output.WriteBool(Compressed);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (HasResult) {
          output.WriteRawTag(8);
          output.WriteUInt32(Result);
        }
        if (HasDepotId) {
          output.WriteRawTag(16);
          output.WriteUInt32(DepotId);
        }
        if (HasSha) {
          output.WriteRawTag(26);
          output.WriteBytes(Sha);
        }
        if (HasChunkData_) {
          output.WriteRawTag(34);
          output.WriteBytes(ChunkData_);
        }
        if (HasEncrypted) {
          output.WriteRawTag(40);
          output.WriteBool(Encrypted);
        }
        if (HasCompressed) {
          output.WriteRawTag(48);
          output.WriteBool(Compressed);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (HasResult) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
        }
        if (HasDepotId) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DepotId);
        }
        if (HasSha) {
          size += 1 + pb::CodedOutputStream.ComputeBytesSize(Sha);
        }
        if (HasChunkData_) {
          size += 1 + pb::CodedOutputStream.ComputeBytesSize(ChunkData_);
        }
        if (HasEncrypted) {
          size += 1 + 1;
        }
        if (HasCompressed) {
          size += 1 + 1;
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(ChunkData other) {
        if (other == null) {
          return;
        }
        if (other.HasResult) {
          Result = other.Result;
        }
        if (other.HasDepotId) {
          DepotId = other.DepotId;
        }
        if (other.HasSha) {
          Sha = other.Sha;
        }
        if (other.HasChunkData_) {
          ChunkData_ = other.ChunkData_;
        }
        if (other.HasEncrypted) {
          Encrypted = other.Encrypted;
        }
        if (other.HasCompressed) {
          Compressed = other.Compressed;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 8: {
              Result = input.ReadUInt32();
              break;
            }
            case 16: {
              DepotId = input.ReadUInt32();
              break;
            }
            case 26: {
              Sha = input.ReadBytes();
              break;
            }
            case 34: {
              ChunkData_ = input.ReadBytes();
              break;
            }
            case 40: {
              Encrypted = input.ReadBool();
              break;
            }
            case 48: {
              Compressed = input.ReadBool();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 8: {
              Result = input.ReadUInt32();
              break;
            }
            case 16: {
              DepotId = input.ReadUInt32();
              break;
            }
            case 26: {
              Sha = input.ReadBytes();
              break;
            }
            case 34: {
              ChunkData_ = input.ReadBytes();
              break;
            }
            case 40: {
              Encrypted = input.ReadBool();
              break;
            }
            case 48: {
              Compressed = input.ReadBool();
              break;
            }
          }
        }
      }
      #endif

    }

  }
  #endregion

}

public sealed partial class CMsgClientPeerChunkRequest : pb::IMessage<CMsgClientPeerChunkRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CMsgClientPeerChunkRequest> _parser = new pb::MessageParser<CMsgClientPeerChunkRequest>(() => new CMsgClientPeerChunkRequest());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CMsgClientPeerChunkRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SteammessagesClientlanp2PReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientPeerChunkRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientPeerChunkRequest(CMsgClientPeerChunkRequest other) : this() {
    _hasBits0 = other._hasBits0;
    appId_ = other.appId_;
    depotId_ = other.depotId_;
    sha_ = other.sha_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientPeerChunkRequest Clone() {
    return new CMsgClientPeerChunkRequest(this);
  }

  /// <summary>Field number for the "app_id" field.</summary>
  public const int AppIdFieldNumber = 1;
  private readonly static uint AppIdDefaultValue = 0;

  private uint appId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint AppId {
    get { if ((_hasBits0 & 1) != 0) { return appId_; } else { return AppIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      appId_ = value;
    }
  }
  /// <summary>Gets whether the "app_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAppId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "app_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAppId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "depot_id" field.</summary>
  public const int DepotIdFieldNumber = 2;
  private readonly static uint DepotIdDefaultValue = 0;

  private uint depotId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint DepotId {
    get { if ((_hasBits0 & 2) != 0) { return depotId_; } else { return DepotIdDefaultValue; } }
    set {
      _hasBits0 |= 2;
      depotId_ = value;
    }
  }
  /// <summary>Gets whether the "depot_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDepotId {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "depot_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDepotId() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "sha" field.</summary>
  public const int ShaFieldNumber = 3;
  private readonly static pb::ByteString ShaDefaultValue = pb::ByteString.Empty;

  private pb::ByteString sha_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Sha {
    get { return sha_ ?? ShaDefaultValue; }
    set {
      sha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "sha" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSha {
    get { return sha_ != null; }
  }
  /// <summary>Clears the value of the "sha" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSha() {
    sha_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CMsgClientPeerChunkRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CMsgClientPeerChunkRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (AppId != other.AppId) return false;
    if (DepotId != other.DepotId) return false;
    if (Sha != other.Sha) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasAppId) hash ^= AppId.GetHashCode();
    if (HasDepotId) hash ^= DepotId.GetHashCode();
    if (HasSha) hash ^= Sha.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasAppId) {
      output.WriteRawTag(8);
      output.WriteUInt32(AppId);
    }
    if (HasDepotId) {
      output.WriteRawTag(16);
      output.WriteUInt32(DepotId);
    }
    if (HasSha) {
      output.WriteRawTag(26);
      output.WriteBytes(Sha);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasAppId) {
      output.WriteRawTag(8);
      output.WriteUInt32(AppId);
    }
    if (HasDepotId) {
      output.WriteRawTag(16);
      output.WriteUInt32(DepotId);
    }
    if (HasSha) {
      output.WriteRawTag(26);
      output.WriteBytes(Sha);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasAppId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AppId);
    }
    if (HasDepotId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DepotId);
    }
    if (HasSha) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Sha);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CMsgClientPeerChunkRequest other) {
    if (other == null) {
      return;
    }
    if (other.HasAppId) {
      AppId = other.AppId;
    }
    if (other.HasDepotId) {
      DepotId = other.DepotId;
    }
    if (other.HasSha) {
      Sha = other.Sha;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          AppId = input.ReadUInt32();
          break;
        }
        case 16: {
          DepotId = input.ReadUInt32();
          break;
        }
        case 26: {
          Sha = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          AppId = input.ReadUInt32();
          break;
        }
        case 16: {
          DepotId = input.ReadUInt32();
          break;
        }
        case 26: {
          Sha = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class CMsgClientPeerChunkResponse : pb::IMessage<CMsgClientPeerChunkResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CMsgClientPeerChunkResponse> _parser = new pb::MessageParser<CMsgClientPeerChunkResponse>(() => new CMsgClientPeerChunkResponse());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CMsgClientPeerChunkResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SteammessagesClientlanp2PReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientPeerChunkResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientPeerChunkResponse(CMsgClientPeerChunkResponse other) : this() {
    _hasBits0 = other._hasBits0;
    result_ = other.result_;
    appId_ = other.appId_;
    depotId_ = other.depotId_;
    sha_ = other.sha_;
    encrypted_ = other.encrypted_;
    compressed_ = other.compressed_;
    chunkData_ = other.chunkData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientPeerChunkResponse Clone() {
    return new CMsgClientPeerChunkResponse(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private readonly static uint ResultDefaultValue = 0;

  private uint result_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Result {
    get { if ((_hasBits0 & 1) != 0) { return result_; } else { return ResultDefaultValue; } }
    set {
      _hasBits0 |= 1;
      result_ = value;
    }
  }
  /// <summary>Gets whether the "result" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasResult {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "result" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearResult() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "app_id" field.</summary>
  public const int AppIdFieldNumber = 2;
  private readonly static uint AppIdDefaultValue = 0;

  private uint appId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint AppId {
    get { if ((_hasBits0 & 2) != 0) { return appId_; } else { return AppIdDefaultValue; } }
    set {
      _hasBits0 |= 2;
      appId_ = value;
    }
  }
  /// <summary>Gets whether the "app_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAppId {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "app_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAppId() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "depot_id" field.</summary>
  public const int DepotIdFieldNumber = 3;
  private readonly static uint DepotIdDefaultValue = 0;

  private uint depotId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint DepotId {
    get { if ((_hasBits0 & 4) != 0) { return depotId_; } else { return DepotIdDefaultValue; } }
    set {
      _hasBits0 |= 4;
      depotId_ = value;
    }
  }
  /// <summary>Gets whether the "depot_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDepotId {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "depot_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDepotId() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "sha" field.</summary>
  public const int ShaFieldNumber = 4;
  private readonly static pb::ByteString ShaDefaultValue = pb::ByteString.Empty;

  private pb::ByteString sha_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Sha {
    get { return sha_ ?? ShaDefaultValue; }
    set {
      sha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "sha" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSha {
    get { return sha_ != null; }
  }
  /// <summary>Clears the value of the "sha" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSha() {
    sha_ = null;
  }

  /// <summary>Field number for the "encrypted" field.</summary>
  public const int EncryptedFieldNumber = 5;
  private readonly static bool EncryptedDefaultValue = false;

  private bool encrypted_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Encrypted {
    get { if ((_hasBits0 & 8) != 0) { return encrypted_; } else { return EncryptedDefaultValue; } }
    set {
      _hasBits0 |= 8;
      encrypted_ = value;
    }
  }
  /// <summary>Gets whether the "encrypted" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasEncrypted {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "encrypted" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearEncrypted() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "compressed" field.</summary>
  public const int CompressedFieldNumber = 6;
  private readonly static bool CompressedDefaultValue = false;

  private bool compressed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Compressed {
    get { if ((_hasBits0 & 16) != 0) { return compressed_; } else { return CompressedDefaultValue; } }
    set {
      _hasBits0 |= 16;
      compressed_ = value;
    }
  }
  /// <summary>Gets whether the "compressed" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCompressed {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "compressed" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCompressed() {
    _hasBits0 &= ~16;
  }

  /// <summary>Field number for the "chunk_data" field.</summary>
  public const int ChunkDataFieldNumber = 7;
  private readonly static pb::ByteString ChunkDataDefaultValue = pb::ByteString.Empty;

  private pb::ByteString chunkData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString ChunkData {
    get { return chunkData_ ?? ChunkDataDefaultValue; }
    set {
      chunkData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "chunk_data" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasChunkData {
    get { return chunkData_ != null; }
  }
  /// <summary>Clears the value of the "chunk_data" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearChunkData() {
    chunkData_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CMsgClientPeerChunkResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CMsgClientPeerChunkResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Result != other.Result) return false;
    if (AppId != other.AppId) return false;
    if (DepotId != other.DepotId) return false;
    if (Sha != other.Sha) return false;
    if (Encrypted != other.Encrypted) return false;
    if (Compressed != other.Compressed) return false;
    if (ChunkData != other.ChunkData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasResult) hash ^= Result.GetHashCode();
    if (HasAppId) hash ^= AppId.GetHashCode();
    if (HasDepotId) hash ^= DepotId.GetHashCode();
    if (HasSha) hash ^= Sha.GetHashCode();
    if (HasEncrypted) hash ^= Encrypted.GetHashCode();
    if (HasCompressed) hash ^= Compressed.GetHashCode();
    if (HasChunkData) hash ^= ChunkData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasResult) {
      output.WriteRawTag(8);
      output.WriteUInt32(Result);
    }
    if (HasAppId) {
      output.WriteRawTag(16);
      output.WriteUInt32(AppId);
    }
    if (HasDepotId) {
      output.WriteRawTag(24);
      output.WriteUInt32(DepotId);
    }
    if (HasSha) {
      output.WriteRawTag(34);
      output.WriteBytes(Sha);
    }
    if (HasEncrypted) {
      output.WriteRawTag(40);
      output.WriteBool(Encrypted);
    }
    if (HasCompressed) {
      output.WriteRawTag(48);
      output.WriteBool(Compressed);
    }
    if (HasChunkData) {
      output.WriteRawTag(58);
      output.WriteBytes(ChunkData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasResult) {
      output.WriteRawTag(8);
      output.WriteUInt32(Result);
    }
    if (HasAppId) {
      output.WriteRawTag(16);
      output.WriteUInt32(AppId);
    }
    if (HasDepotId) {
      output.WriteRawTag(24);
      output.WriteUInt32(DepotId);
    }
    if (HasSha) {
      output.WriteRawTag(34);
      output.WriteBytes(Sha);
    }
    if (HasEncrypted) {
      output.WriteRawTag(40);
      output.WriteBool(Encrypted);
    }
    if (HasCompressed) {
      output.WriteRawTag(48);
      output.WriteBool(Compressed);
    }
    if (HasChunkData) {
      output.WriteRawTag(58);
      output.WriteBytes(ChunkData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasResult) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
    }
    if (HasAppId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AppId);
    }
    if (HasDepotId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DepotId);
    }
    if (HasSha) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Sha);
    }
    if (HasEncrypted) {
      size += 1 + 1;
    }
    if (HasCompressed) {
      size += 1 + 1;
    }
    if (HasChunkData) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(ChunkData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CMsgClientPeerChunkResponse other) {
    if (other == null) {
      return;
    }
    if (other.HasResult) {
      Result = other.Result;
    }
    if (other.HasAppId) {
      AppId = other.AppId;
    }
    if (other.HasDepotId) {
      DepotId = other.DepotId;
    }
    if (other.HasSha) {
      Sha = other.Sha;
    }
    if (other.HasEncrypted) {
      Encrypted = other.Encrypted;
    }
    if (other.HasCompressed) {
      Compressed = other.Compressed;
    }
    if (other.HasChunkData) {
      ChunkData = other.ChunkData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Result = input.ReadUInt32();
          break;
        }
        case 16: {
          AppId = input.ReadUInt32();
          break;
        }
        case 24: {
          DepotId = input.ReadUInt32();
          break;
        }
        case 34: {
          Sha = input.ReadBytes();
          break;
        }
        case 40: {
          Encrypted = input.ReadBool();
          break;
        }
        case 48: {
          Compressed = input.ReadBool();
          break;
        }
        case 58: {
          ChunkData = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Result = input.ReadUInt32();
          break;
        }
        case 16: {
          AppId = input.ReadUInt32();
          break;
        }
        case 24: {
          DepotId = input.ReadUInt32();
          break;
        }
        case 34: {
          Sha = input.ReadBytes();
          break;
        }
        case 40: {
          Encrypted = input.ReadBool();
          break;
        }
        case 48: {
          Compressed = input.ReadBool();
          break;
        }
        case 58: {
          ChunkData = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
